Rails.application.routes.draw do
    root 'states#irco'
    post 'states/load_irco'
    post 'counties/load_irco'
    get 'counties/low_risk'
    get 'counties/high_risk'
    get 'counties/destinations'
    get 'counties/irco'
    get 'states/irco'
    get 'state_victims_api' => 'datasets#state_victims_api'
    get 'county_victims_api' => 'datasets#county_victims_api'
    get 'year_victims_api' => 'datasets#year_victims_api'
    get 'loadApi' => 'datasets#loadApi'
    get 'organizations/index'
    post 'members/detentions'
    get 'members/detainees'
    get 'members/detainees_query'
    get 'quarters/ispyv'
    get 'months/reports' => 'months#reports'
    get 'datasets/show'
    get 'datasets/load'
    get 'sources/twitter'
    get 'organizations/dictionary'
    post 'organizations/load_organizations'
    post 'organizations/load_organization_events'
    post 'organizations/load_organization_territory'
    get 'queries/mapOff'
    get 'queries/mapOn'
    get 'password' => 'organizations#password'
    get 'organizations/logout' => 'organizations#logout'
    post 'organizations/login' => 'organizations#login'
    get 'intro' => 'users#intro'
    get 'organizations/main' => 'organizations#main'
    post 'counties/getCounties' => 'counties#getCounties'
    post 'towns/getTowns' => 'towns#getTowns'
    get 'sources/twitter'=>'sources#twitter'
    get 'events/killings'=>'events#killings'
    post 'events/create_killing'=>'events#create_killing'
    get 'events/victims/:killed_count' => 'events#victims'
    post 'events/create_victim' => 'events#create_victims'
    post 'events/create_single_victim' => 'events#create_single_victim'
    get 'organizations/new' => 'organizations#new'
    post 'organizations/create_organization' => 'organizations#create_organization'
    post 'organizations/getDivisions' => 'organizations#getDivisions'
    post 'organizations/getMembers/:organization_id' => 'organizations#getMembers' 
    get 'send_query' => 'events#send_query'
    post 'send_query' => 'events#send_query'
    get 'pageback/:index' => 'queries#pageback'
    get 'pageforward/:index' => 'queries#pageforward'
    get 'pageback' => 'events#pageback'
    get 'pageforward' => 'events#pageforward'
    post 'queries/get_months' => 'queries#get_months'
    post 'queries/get_regular_months' => 'queries#get_regular_months'
    post 'queries/get_quarters' => 'queries#get_quarters'
    post 'states/getStates' => 'states#getStates'
    post 'states/getCities' => 'states#getCities'
    get 'queries/files' =>'queries#files'
    get 'queries/send_file/:catalogue/:extension' => 'queries#send_file'
    get 'queries/send_query_file/:extension' => 'queries#send_query_file'
    get 'queries/test_xlsx' => 'queries#test_xlsx', as: "test"
    post 'datasets/load_ensu' 
    post 'months/load_violence_report' 
    post 'months/load_crime_victim_report' 
    post 'months/header_selector/:month' => 'months#header_selector'
    get 'datasets/victims_query'
    post 'datasets/victims_query' => 'datasets#post_victim_query'
    post 'members/detainees_query' => 'members#post_detainees_query'
    post 'organizations/organizations_query' => 'organizations#post_query'
    get 'datasets/victims'
    get 'datasets/basic'
    get 'datasets/:type/:cell' => 'datasets#sort'
    post 'counties/getCheckboxCounties/:id' => 'counties#getCheckboxCounties'
    get 'organizations/show/:id' => 'organizations#show'
    get 'organizations/query' => 'organizations#query'
    get 'counties/set_index_county/:id' => 'counties#set_index_county'
end
