myLeagues = [
	{
		:name=>"Cártel",
		:description=>"Los cárteles son una confederación de mafias o familias criminales que funcionan con cierta independencia, pero están sujetas a las decisiones de una serie de liderazgos; en buena medida, porque todavía funcionan con un modelo empresarial de corte familiar. Esta capacidad de coordinación les permite generar economías de escala, operar en varias regiones o en la totalidad del país, enfrentarse exitosamente como milicias contra rivales en los mercados ilegales en los que participan, y dedicarse casi exclusivamente a la producción y exportación de drogas; aunque también participan en el mercado formal de distintas maneras, con el auxilio de actividades de lavado de dinero o como profesionales de la violencia para empresas, por ejemplo. Los cárteles suelen presentar una estructura jerárquica en niveles no del todo claros: en el pináculo se encuentra la dirigencia integrada por los principales miembros de las familias que fundaron la organización (líderes o capos), donde existe una decisión colegiada. Después, en segundo término, están los encargados de áreas de influencia o de operación (“jefes de plaza”), o de ciertas actividades (“jefes de seguridad”, contadores y abogados), y familiares en segundo grado, amigos o conocidos. En el tercero están los profesionales de la violencia o brazos armados (asesinos o sicarios), distribuidores y vendedores, vigilantes (“halcones”) o pandillas afines. El parentesco y compadrazgo son bases importantes para establecer alianzas y para legitimar autoridad. Con base en estos criterios se logra cohesión y solidaridad internas. Actualmente, a pesar de que muchos se nombren de esa manera, en México podría afirmarse que sólo existen dos cárteles: el Cártel del Pacífico (como lo conoce el Estado mexicano en el ámbito de la inteligencia) o Cártel de Sinaloa (como también se autonombran sus integrantes); y el Cártel Jalisco Nueva Generación (CJNG)."

	},{
		:name=>"Mafia",
		:description=>"Las mafias son organizaciones de corte regional usualmente conformadas por uno o más grupos criminales y con presencia en uno o más estados. Pueden ser parte de cárteles, o subcontratarse a estos, o trabajar de forma independiente en actividades de narcomenudeo, producción de narcóticos u otros mercados negros (contrabando de mercancías o bienes perecederos, o elaboración y comercialización de productos apócrifos) y actividades delictivas de alto impacto como el secuestro (levantones) y la extorsión (presencial-cobro de derecho de piso). A pesar de sus integrantes tienen lazos familiares o de amistad, tienen una estructura menos jerárquica que los cárteles y más fragmentada; por tanto, tienden a ser más inestables en el largo plazo, causando bifurcaciones y conflictos internos frecuentes. La consolidación territorial de las mafias en los ámbitos regional y local requiere de un uso más intensivo de la violencia. Esto se debe a dos motivos: por un lado, deben imponerse a varias agrupaciones que disputan los mismos mercados ilegales; y, por otro, están obligadas a crear una reputación de violencia para controlar estos mercados. Esta reputación les garantiza los pagos de rescates (secuestros) o extorsiones presenciales (cobro de derecho de piso), y también se evita que las víctimas colaboren con autoridades o con sus rivales. Y aunque las mafias no tienen los recursos ni la capacidad para sobornar, salvo excepciones, a autoridades estatales o federales — y son, por tanto, más vulnerables a la persecución del Estado—, sí cuentan con capacidad de interlocución y soborno en el ámbito local (ayuntamientos y policías municipales)."
	},{
		:name=>"Banda",
		:description=>"Las bandas son organizaciones criminales con presencia meramente local, usualmente en ciudades, municipios o en parte de una región. Suelen dedicarse a delitos menores como el narcomenudeo o del fuero común como los robos de comercio o vehículo. No tienen las habilidades corruptoras como los cárteles o las mafias. En ese sentido, sus capacidades económicas y armamentísticas son limitadas por lo que suelen recurrir a mafias o a carteles para abastecerse de insumos como narcóticos o armas de fuego; como tal también se subcontratan o fungen como brazos armados de las mafias o cárteles, ya sea para representarlos en actividades de narcomenudeo, ajuste de cuentas (ejecuciones premeditadas), extorsión presencial (cobro de derecho de piso) o controlando el autogobierno de los centros penitenciarios."
	},{
		:name=>"Brazo armado",
		:description=>"Se trata del grupo de profesionales de la violencia (sicarios) de los cárteles y mafias. En el caso de las mafias se trata de grupos que son parte de la estructura de la organización, mientras que en el caso de los cárteles suelen ser cuerpos de reserva conformado por sicarios o profesionales de la violencia otorgados o cedidos voluntariamente por las mafias o células que componen al cártel con el objetivo de participar en operaciones contra enemigos externos."
	},{
		:name=>"Célula",
		:description=>"Las células son mafias que forman parte de una confederación de grupos criminales o cártel con el fin de dominar ciertos mercados ilegales y defenderlos de enemigos comunes y externos. En otras palabras, son una especie de franquicia, entendida como un grupo o familia criminal al que un cártel les concedió derechos de explotación de actividades delictivas en una zona determinada a nombre del cártel (es decir, tienen control sobre una “plaza”); sin embargo, no necesariamente reciben órdenes de un “capo” o líder — de hecho, los líderes de las células pueden ser parte de la decisión colegiada del cártel—, pues cuentan con autonomía de gestión siempre y cuando respeten una serie de reglas y acuerdos básicos respecto al posicionamiento del cártel frente a rivales externos, por ejemplo. Así, su pertenencia a un cartel se define mediante el vínculo comercial, familiar o de amistad que tiene el grupo con algún liderazgo o capo en particular."
	},{
		:name=>"Escisión",
		:description=>"Actualmente la mayoría de las mafias en México son bifurcaciones, rompimientos o fragmentos de antiguos cárteles como Los Zetas, El Cártel del Golfo, la organización criminal de Los Beltrán Leyva (OCBL), La Familia Michoacana y Los Caballeros Templarios. En ese sentido, la OCBL, por ejemplo, no es actualmente una organización criminal cohesionada, sino varias sin liderazgo claro e incluso antagónicas entre sí: ejemplo de ello son El Cártel Independiente de Acapulco (CIDA) y Sierra Unida Revolucionaria (SUR)- Cártel del Sur —ambos grupos criminales con presencia en Guerrero y provenientes de la OCBL, pero antagónicos entre sí."
	},{
		:name=>"Pandilla",
		:description=>"Las pandillas son grupos de individuos que adoptan una identidad colectiva para crear una atmósfera de miedo, intimidación o respeto. En ese sentido, el elemento reputacional es clave en la definición, así como el sentido de pertenencia; por eso, suelen tener un nombre común, eslogan, un símbolo o señal de identificación (como tatuajes o marcas físicas, estilos o colores de vestimenta determinados, cortes de pelo, señal de saludo o grafitis particulares). Su presencia se limita a centros penitenciarios, barrios o calles en una ciudad o población en específico."
	}
]
myLeagues.each{|league|
	relevant = League.where(:name=>league[:name])
	if relevant.empty?
		League.create(league)
	else
		relevant.update(league)
	end
}

	
