require 'csv'

# 🔽 Pega aquí todo el contenido del archivo CSV (incluyendo los encabezados)
csv_data = <<~CSV
legacy_id,fecha,estado,municipio o localidad,clave INEGI,título,reporte,link
BC-1,2018-01-20,Baja California,Tijuana,2004,Presunto integrante del CJNG es detenido por agentes de la PEP,,https://conexionsi.com/2018/01/20/presunto-integrante-del-cjng-es-detenido-por-agentes-de-la-pep/
BC-2,2018-01-19,Baja California,Tijuana,2004,Detienen a presunto integrante del CJNG en Tijuana,,https://www.tijuanaenlinea.com/policiaca/2018/01/19/detienen-a-presunto-integrante-del-cjng-en-tijuana/
BC-3,2018-09-01,Baja California,Tijuana,2004,Territorial Tensions: Explaining Baja California's Recent Wave of Violence,,https://www.strausscenter.org/wp-content/uploads/Territorial-Tensions-Explaining-Baja-Californias-Recent-Wave-of-Violence-2018.pdf
BC-4,2018-02-08,Colima,Tecomán,6010,Fighting for the Plaza: CDS Vs CJNG in Pacific States,,https://www.borderlandbeat.com/2018/02/fighting-for-plaza-cds-vs-cjng-in.html
BC-5,2018-03-15,Baja California,Tijuana,2004,Border Violence: The Most Wanted CJNG Sicarios in Baja California,,https://rightsidenews.com/us/homeland-security/border-violence-the-most-wanted-cjng-sicarios-in-baja-california/
BC-6,2025-01-29,Baja California,Ensenada,2003,CJNG deja cabeza humana con narcomensaje para Los Mayos y Los Chapitos en Ensenada,,https://www.infobae.com/mexico/2025/01/29/cjng-deja-cabeza-humana-con-narcomensaje-para-los-mayos-y-los-chapitos-en-ensenada-no-son-bienvenidos/
BC-7,2019-08-27,Baja California,Tecate,2005,Internal Strife Within the CJNG in Baja California; Mexico,,https://insightcrime.org/news/internal-strife-cjng-baja-california-mexico/
BC-8,2025-04-15,Jalisco,Guadalajara,14039,CJNG: la ruta sangrienta con la que dominó México y cruzó fronteras,,https://www.milenio.com/policia/narcotrafico/cjng-por-que-se-expandio-en-mexico-ciudades-clave-eu
BC-9,2018-03-01,Baja California,Tijuana,2004,El organigrama de líder del CJNG en Baja California,,https://www.narcoenmexico.com/2018/03/el-organigrama-de-lider-del-cjng-en.html
BC-10,2019-08-29,Baja California,Tecate,2005,Pugnas en el CJNG y la aparición de otro grupo (Los Cabos) avivan ola violencia en Baja California,,https://www.sinembargo.mx/3636898/pugnas-en-el-cjng-y-la-aparicion-de-otro-grupo-los-cabos-avivan-ola-violencia-en-baja-california/
BC-11,2018-04-15,Jalisco,Guadalajara,14039,The Strategic Implications of the Cartel de Jalisco Nueva Generacion,,https://www.researchgate.net/publication/324579843_The_Strategic_Implications_of_the_Cartel_de_Jalisco_Nueva_Generacion
BC-12,2023-10-01,Jalisco,Guadalajara,14039,Cartel de Jalisco Nueva Generación: The most significant security challenge in the Mexico-United States relationship,,https://smallwarsjournal.com/2023/10/01/cartel-de-jalisco-nueva-generacion-most-significant-security-challenge-mexico-united/
BC-13,2024-09-29,Jalisco,Guadalajara,14039,Presente y futuro del CJNG: Consolidación local; expansión militar y retórica de autodefensa,,https://insightcrime.org/es/noticias/analisis/cjng-consolidacion-local-expansion-militar-retorica-vigilante/
BC-14,2024-09-29,Jalisco,Guadalajara,14039,Mexico's CJNG: Local Consolidation; Military Expansion and Vigilante Rhetoric,,https://insightcrime.org/news/mexico-cjng-local-consolidation-military-expansion-vigilante-rhetoric/
BC-15,2019-08-27,Baja California,Tecate,2005,Internal Strife Within the CJNG in Baja California; Mexico,,https://compuseum.org/news/brief/internal-strife-cjng-baja-california-mexico/
BC-16,2018-07-02,Baja California,Tijuana,2004,Los delincuentes trasnacionales del CJNG,,https://zetatijuana.com/2018/07/los-delincuentes-trasnacionales-del-cjng/
BC-17,2018-06-22,Baja California,Tijuana,2004,CJNG increasing the violence in BC,,https://www.borderlandbeat.com/2018/06/cjng-increasing-violence-in-bc.html
BC-18,2025-03-27,Baja California,Tecate,2005,Presuntos miembros del CJNG amenazan al alcalde de Tecate; Baja California,,https://www.infobae.com/mexico/2025/03/27/presuntos-miembros-del-cjng-amenazan-al-alcalde-de-tecate-baja-california-el-que-avisa-no-es-traidor/
BC-19,2018-03-16,Baja California,Tijuana,2004,Capturan a 18 presuntos miembros del CJNG,,https://www.tijuanaenlinea.com/nacional/2018/03/16/capturan-a-18-presuntos-miembros-del-cjng/
BC-20,2025-03-20,Jalisco,Guadalajara,14039,Cronología del CJNG en Jalisco: 12 años de terror que dejaron 13 mil desaparecidos,,https://www.infobae.com/mexico/2025/03/20/cronologia-del-cjng-en-jalisco-12-anos-de-terror-que-dejaron-13-mil-desaparecidos/
BC-21,2022-08-23,Baja California,Tijuana,2004,¿Quiénes son los 20 integrantes del CJNG que desataron bloqueos y quemas en BC?,,https://www.sinembargo.mx/4242598/quienes-son-los-20-integrantes-del-cjng-que-desataron-bloqueos-y-quemas-en-bc/
BC-22,2018-04-05,Baja California,Tijuana,2004,Los asesinatos del CJNG,,https://zetatijuana.com/2018/04/los-asesinatos-del-cjng/
BC-23,2024-09-10,Jalisco,Guadalajara,14039,Where is the CJNG in Mexico,,https://www.seasonsofcrime.com/p/where-is-the-cjng-in-mexico
BC-24,2025-03-19,Jalisco,Guadalajara,14039,Gerardo Ortiz: ¿quién es el intérprete que se declaró culpable de cantar en conciertos vinculados con el CJNG?,,https://www.proceso.com.mx/nacional/justicia/2025/3/19/gerardo-ortiz-quien-es-el-interprete-que-se-declaro-culpable-de-cantar-en-conciertos-vinculados-con-el-cjng-347708.html
BC-25,2020-07-15,Baja California,Tijuana,2004,El CJNG se divide: células en BC brincan a los Arellano Félix y a Los Erres del Cártel de Sinaloa,,https://www.sinembargo.mx/3840371/el-cjng-se-divide-celulas-en-bc-brincan-a-los-arellano-felix-y-a-los-erres-del-cartel-de-sinaloa/
BC-26,2018-01-01,Baja California,Tijuana,2004,CJNG avanza en 22 estados,,https://zetatijuana.com/2018/01/cjng-avanza-en-22-estados/
BC-27,2022-08-15,Baja California,Tijuana,2004,CJNG: cómo la organización criminal habría utilizado a personas sin hogar para incendiar vehículos en Baja California,,https://www.prensalibre.com/internacional/cjng-como-la-organizacion-criminal-habria-utilizado-a-personas-sin-hogar-para-incendiar-vehiculos-en-baja-california-y-cuanto-les-pagaron-por-estos-ataques/
BC-28,2018-08-10,Baja California,Tijuana,2004,El Mayo is behind division of CJNG,,https://www.borderlandbeat.com/2018/08/el-mayo-is-behind-division-of-cjng.html
BC-29,2025-01-22,Baja California,Tijuana,2004,Narcomanta en Tijuana: CJNG y La Chapiza declaran guerra a La Mayiza,,https://laverdadnoticias.com/crimen/narcomanta-en-tijuana-cjng-y-la-chapiza-declaran-guerra-a-la-mayiza-20250122
BC-30,2021-02-02,Baja California,Tijuana,2004,El desafío de los Chapitos en Baja California: reclutaron a operadores del Mencho y ejecutaron a los jefes de plaza del Mayo,,https://www.infobae.com/america/mexico/2021/02/02/el-desafio-de-los-chapitos-en-baja-california-reclutaron-a-operadores-del-mencho-y-ejecutaron-a-los-jefes-de-plaza-del-mayo/
BC-31,2018-10-01,Baja California,Tijuana,2004,Matan a lugarteniente del CJNG; BC con más ejecuciones que en 2017,,https://zetatijuana.com/2018/10/matan-a-lugarteniente-del-cjng-bc-con-mas-ejecuciones-que-en-2017/
BC-32,2018-08-08,Jalisco,Guadalajara,14039,Repunta casi 2000% violencia en estados bastiones del CJNG,,https://elblogdelnarco.com/2018/08/08/repunta-casi-2000-violencia-en-estados-bastiones-del-cjng/
BC-33,2018-06-22,Baja California,Tijuana,2004,CJNG increasing the violence in BC,,https://www.borderlandbeat.com/2018/06/cjng-increasing-violence-in-bc.html?m=1
BC-34,2018-06-15,Baja California,Tijuana,2004,La pugna del CJNG y CAF anda a punta de balazos,,https://www.narcoenmexico.com/2018/06/la-pugna-del-cjng-y-caf-anda-apunta-de.html
BC-35,2022-08-13,Baja California,Tijuana,2004,Por violencia del CJNG en Baja California; piden a ciudadanos de EE. UU. que se refugien,,https://www.univision.com/local/los-angeles-kmex/violencia-baja-california-tijuana-consulado-de-estados-unidos-fotos
BC-36,2018-10-16,Texas,El Paso,48041,Indictments against 11 high level Mexican drug cartel members unsealed,,https://www.dea.gov/press-releases/2018/10/16/indictments-against-11-high-level-mexican-drug-cartel-members-unsealed
BC-37,2018-07-26,Veracruz,Veracruz,30119,Vídeo donde El Fredy de Los Zetas confiesa sus crímenes y después es ejecutado por El CJNG,,https://elblogdelnarco.com/2018/07/26/
BC-38,2024-03-01,Quintana Roo,Cancún,23005,De Baja California a Quintana Roo: Así fue la expansión del CJNG en el gobierno de AMLO,,https://www.periodicobajacalifornia.info/nacional/de-baja-california-a-quintana-roo-asi-fue-la-expansion-del-cjng-en-el-gobierno-de-amlo-2
BC-39,2023-07-12,Baja California,Tijuana,2004,Detienen a presuntos traficantes internacionales del CJNG,,https://www.telediario.mx/nacional/detienen-a-presuntos-traficantes-internacionales-del-cjng
BC-40,2023-08-03,Baja California,Tijuana,2004,¿Quién es El Caimán; sanguinario líder del brazo armado del CJNG que fue extraditado a EE.UU.?,,https://www.infobae.com/mexico/2023/08/03/quien-es-el-caiman-sanguinario-lider-del-brazo-armado-del-cjng-que-fue-extraditado-a-eeuu/
BC-41,2023-08-04,Baja California,Tijuana,2004,Edgar Herrera Pardo; alias El Caimán; también es conocido como El Cabo 8,,https://www.tvazteca.com/aztecanoticias/edgar-herrera-pardo-alias-el-caiman-tambien-es-conocido-como-el-cabo-8
BC-42,2022-08-13,Baja California,Tijuana,2004,Detuvieron a 17 por violencia en Baja California; 3 son del CJNG,,https://www.tiempo.com.mx/noticia/bajacalifornia_detener_cjng_bloqueos_delitos_guardianacional/
BC-43,2020-09-07,Baja California,Tijuana,2004,En la violenta guerra entre CJNG y CDS,,https://zetatijuana.com/2020/09/en-la-violenta-guerra-entre-cjng-y-cds/
BC-44,2022-08-13,Baja California,Tijuana,2004,CJNG operó ataques en Baja California,,https://www.elmanana.com/noticias/nacional/cjng-opero-ataques-en-baja-california/5586918
BC-45,2022-08-13,Baja California,Tijuana,2004,CJNG operó ataques en BC; afirman alcaldes,,https://www.elnorte.com/cjng-opero-ataques-en-bc-afirman-alcaldes/ar2453036
BC-46,2018-10-16,Baja California,Tijuana,2004,Alleged Tijuana leader of powerful CJNG drug trafficking group named in wave of indictments,,https://www.sandiegouniontribune.com/2018/10/16/alleged-tijuana-leader-of-powerful-cjng-drug-trafficking-group-named-in-wave-of-indictments/
BC-47,2024-09-02,Jalisco,Guadalajara,14039,Mexico Institutional Failures Allow CJNG to Thrive Unchecked,,https://insightcrime.org/news/mexico-failures-cjng-thrive/
BC-48,2018-10-16,Washington,D.C.,0,Justice;Treasury; and State Departments announce coordinated enforcement efforts against Cartel Jalisco Nueva Generacion,,https://www.dea.gov/press-releases/2018/10/16/justice-treasury-and-state-departments-announce-coordinated-enforcement
BC-49,2022-01-05,Baja California,Tijuana,2004,Tijuana: Human Head Left With Threats for CJNG's Cabo 30 and Cabo 50,,https://www.borderlandbeat.com/2022/01/tijuana-human-head-left-with-threats.html
BC-50,2021-09-15,Baja California,Tijuana,2004,Golpe al CJNG: capturaron por segunda ocasión al Cabo 89; jefe de plaza en Baja California,,https://www.infobae.com/america/mexico/2021/09/15/golpe-al-cjng-capturaron-por-segunda-ocasion-al-cabo-89-jefe-de-plaza-en-baja-california/
BC-51,2021-06-16,Baja California,Tijuana,2004,Los Cabos del Cártel Jalisco Nueva Generación: los rostros detrás de la violencia en el norte del país,,https://www.infobae.com/america/mexico/2021/06/16/los-cabos-del-cartel-jalisco-nueva-generacion-los-rostros-detras-de-la-violencia-en-el-norte-del-pais/
BC-52,2022-08-13,Baja California,Tijuana,2004,Atribuyen al CJNG actos de violencia en Baja California; detienen a 15 presuntos responsables,,https://www.jorgecastronoriega.com/atribuyen-al-cjng-actos-de-violencia-en-baja-california-detienen-a-15-presuntos-responsables/
BCS-01,2018-01-07,Baja California Sur,,3,Los grupos criminales que se disputan el control de BCS,,https://lasillarota.com/estados/2018/1/7/los-grupos-criminales-que-se-disputan-el-control-de-bcs-149098.html
BCS-02,2018-01-13,México,,0,CJNG avanza en 22 estados,,https://zetatijuana.com/2018/01/cjng-avanza-en-22-estados/
BCS-03,2018-02-04,Baja California,,2,PGR tras el CJNG en BC,,https://zetatijuana.com/2018/02/pgr-tras-el-cjng-en-bc/
BCS-04,2018-02-06,Baja California,,2,Internal Strife Splinters CJNG in Baja California; Mexico,,https://insightcrime.org/news/internal-strife-cjng-baja-california-mexico/
BCS-05,2018-06-18,Baja California,,2,CJNG Increasing Violence in BC,,https://www.borderlandbeat.com/2018/06/cjng-increasing-violence-in-bc.html
BCS-06,2025-01-29,Baja California,Ensenada,2003,CJNG deja cabeza humana con narcomensaje para los Mayos y los Chapitos en Ensenada; 'No son bienvenidos',,https://www.infobae.com/mexico/2025/01/29/cjng-deja-cabeza-humana-con-narcomensaje-para-los-mayos-y-los-chapitos-en-ensenada-no-son-bienvenidos/
BCS-07,2018-03-12,Jalisco,Guadalajara,14039,El organigrama del líder del CJNG en México,,https://www.narcoenmexico.com/2018/03/el-organigrama-de-lider-del-cjng-en.html
BCS-08,2023-11-15,México,,0,Where is the CJNG in Mexico?,,https://www.seasonsofcrime.com/p/where-is-the-cjng-in-mexico
BCS-09,2018-04-18,Baja California Sur,,3,The Strategic Implications of the Cartel de Jalisco Nueva Generación,,https://www.researchgate.net/publication/324579843_The_Strategic_Implications_of_the_Cartel_de_Jalisco_Nueva_Generacion
BCS-10,2019-08-27,Baja California,,2,Pugna dentro del CJNG llega a Baja California; México,,https://insightcrime.org/es/noticias/pugna-cjng-baja-california-mexico/
BCS-11,2018-02-08,Baja California,,2,Fighting for the Plaza: CDS Vs CJNG in Pacific States,,https://www.borderlandbeat.com/2018/02/fighting-for-plaza-cds-vs-cjng-in.html
BCS-12,2018-02-10,Baja California,,2,CJNG lidera trasiego de drogas a EU; nació como Los Matazetas,,https://www.excelsior.com.mx/nacional/2018/02/10/1219402
BCS-13,2018-02-08,Baja California Sur,,3,Mexico’s CJNG: Local Consolidation; Military Expansion and Vigilante Rhetoric,,https://www.academia.edu/35906462/Mexico_s_CJNG_Local_Consolidation_Military_Expansion_and_Vigilante_Rhetoric
BCS-14,2018-03-06,Baja California Sur,,3,Propagación de violencia en México ahora golpea a Baja California Sur,,https://insightcrime.org/es/noticias/propagacion-de-violencia-en-mexico-ahora-golpea-baja-california-sur/
BCS-15,2025-02-21,Baja California,,2,CJNG corresponsable de la crisis de credibilidad que sufren las policías y corporaciones de seguridad,,https://www.infobae.com/mexico/2025/02/21/cjng-corresponsable-de-la-crisis-de-credibilidad-que-sufren-las-policias-y-corporaciones-de-seguridad/
BCS-16,2018-07-02,Baja California,,2,Los delincuentes trasnacionales del CJNG,,https://zetatijuana.com/2018/07/los-delincuentes-trasnacionales-del-cjng/
BCS-17,2018-08-08,Baja California Sur,,3,Repunta casi 2000% violencia en estados bastiones del CJNG,,https://elblogdelnarco.com/2018/08/08/repunta-casi-2000-violencia-en-estados-bastiones-del-cjng/
BCS-18,2018-03-19,México,,0,The Strategic Implications of the Cartel de Jalisco Nueva Generación,,https://justiceinmexico.org/wp-content/uploads/2018/03/180319-Policy_Brief-CJNG.pdf
BCS-19,2018-04-04,Baja California,Mexicali,2002,PEP captura a presunto sicario del CJNG,,https://www.elimparcial.com/tij/policiaca/2018/04/04/pep-captura-a-presunto-sicario-del-cjng/
BCS-20,2025-03-27,Baja California,Tecate,2004,Presuntos miembros del CJNG amenazan al alcalde de Tecate; Baja California: 'El que avisa no es traidor',,https://www.infobae.com/mexico/2025/03/27/presuntos-miembros-del-cjng-amenazan-al-alcalde-de-tecate-baja-california-el-que-avisa-no-es-traidor/
BCS-21,2023-10-01,México,,0,Cartel de Jalisco Nueva Generación: Most Significant Security Challenge to Mexico and the United States,,https://smallwarsjournal.com/2023/10/01/cartel-de-jalisco-nueva-generacion-most-significant-security-challenge-mexico-united/
BCS-22,2023-08-23,Baja California,,2,¿Quiénes son los 20 integrantes del CJNG que desataron bloqueos y quemas en BC?,,https://www.sinembargo.mx/4242598/quienes-son-los-20-integrantes-del-cjng-que-desataron-bloqueos-y-quemas-en-bc/
BCS-23,2020-08-12,Baja California,,2,El CJNG se divide. Células en BC brincan a los Arellano Félix y a 'Los Erres'; del Cártel de Sinaloa,,https://www.sinembargo.mx/3840371/el-cjng-se-divide-celulas-en-bc-brincan-a-los-arellano-felix-y-a-los-erres-del-cartel-de-sinaloa/
BCS-24,2023-03-16,México,,0,CJNG; la organización que domina el crimen en México,,https://news.culturacolectiva.com/noticias/mexico/cartel-jalisco-nueva-generacion-domina-crimen-organizado-en-mexico/
BCS-25,2018-01-02,México,,0,CJNG advances in 22 states,,https://www.borderlandbeat.com/2018/01/cjng-advances-in-22-states.html
BCS-26,2018-07-15,México,,0,La mancha expansiva del CJNG en México,,https://lasillarota.com/especiales-lsr/2018/7/15/la-mancha-expansiva-del-cjng-en-mexico-163979.html
BCS-27,2019-10-01,México,,0,CJNG: Power and Violence Operating in 25 States,,https://www.borderlandbeat.com/2019/10/cjng-power-and-violence-operating-in-25.html
BCS-28,2024-02-29,México,,0,De Baja California a Quintana Roo: así fue la expansión del CJNG en el gobierno de AMLO,,https://www.periodicobajacalifornia.info/nacional/de-baja-california-a-quintana-roo-asi-fue-la-expansion-del-cjng-en-el-gobierno-de-amlo-2
BCS-29,2022-08-16,Baja California,,2,CJNG: cómo la organización criminal habría utilizado a personas sin hogar para incendiar vehículos en Baja California (y cuánto les pagaron),,https://www.prensalibre.com/internacional/cjng-como-la-organizacion-criminal-habria-utilizado-a-personas-sin-hogar-para-incendiar-vehiculos-en-baja-california-y-cuanto-les-pagaron-por-estos-ataques/
BCS-30,2018-08-18,México,,0,CJNG: la PGR dice que es el único que opera; ¿pero es verdad?,,https://da21w.e-veracruz.mx/nota/2018-08-18/nacion/cjng-la-pgr-dice-que-es-el-unico-que-opera-pero-es-verdad
BCS-31,2018-10-16,México,,0,Indictments against 11 high level Mexican drug cartel members unsealed,,https://www.dea.gov/press-releases/2018/10/16/indictments-against-11-high-level-mexican-drug-cartel-members-unsealed
BCS-32,2018-02-08,México,,0,Presente y futuro del CJNG: Consolidación local; expansión militar y retórica de autodefensa,,https://insightcrime.org/es/noticias/analisis/cjng-consolidacion-local-expansion-militar-retorica-vigilante/
BCS-33,2018-09-10,Baja California,,2,Las libertades del CJNG,,https://zetatijuana.com/2018/09/las-libertades-del-cjng/
BCS-34,2018-10-08,Baja California,Tijuana,2004,Matan a lugarteniente del CJNG; BC;con más ejecuciones que en 2017,,https://zetatijuana.com/2018/10/matan-a-lugarteniente-del-cjng-bc-con-mas-ejecuciones-que-en-2017/
BCS-35,2023-08-03,Baja California,Tijuana,2004,Quién es el Caimán; sanguinario líder del brazo armado del CJNG que fue extraditado a EEUU,,https://www.infobae.com/mexico/2023/08/03/quien-es-el-caiman-sanguinario-lider-del-brazo-armado-del-cjng-que-fue-extraditado-a-eeuu/
BCS-36,2018-09-01,Baja California,,2,Territorial Tensions: Explaining Baja California's Recent Wave of Violence,,https://stage2323u9.strausscenter.org/wp-content/uploads/Territorial-Tensions-Explaining-Baja-Californias-Recent-Wave-of-Violence-2018.pdf
BCS-37,2019-10-23,México,,0,CJNG: Power and Violence Operating in 25 States,,https://www.borderlandbeat.com/2019/10/cjng-power-and-violence-operating-in-25.html
CAMP-01,2018,Quintana Roo,Playa del Carmen,23005,2018 Playa del Carmen shootout,,https://historica.fandom.com/wiki/2018_Playa_del_Carmen_shootout
CAMP-02,2024-05-21,México,,,Where is the CJNG in Mexico?,,https://www.seasonsofcrime.com/p/where-is-the-cjng-in-mexico
CAMP-03,2025-04-15,México,,,CJNG: así logró su expansión; principales zonas de operación,,https://www.milenio.com/policia/narcotrafico/cjng-por-que-se-expandio-en-mexico-ciudades-clave-eu
CAMP-04,2019-06-13,Jalisco,,,The School of Terror: Inside a Jalisco Cartel Training Camp in Mexico,,https://insightcrime.org/news/training-grounds-mexico-jalisco-cartel/
CAMP-05,2018-01-10,Yucatán,,,Dan 18 años de prisión a 11 integrantes del CJNG,,https://www.yucatan.com.mx/mexico/2018/01/10/dan-18-anos-prision-11-integrantes-del-cjng.html
CAMP-06,2018-04,México,,,The Strategic Implications of the Cartel de Jalisco Nueva Generacion,,https://www.researchgate.net/publication/324579843_The_Strategic_Implications_of_the_Cartel_de_Jalisco_Nueva_Generacion
CAMP-07,2025-04-18,Jalisco,Teocaltiche,14093,Teocaltiche; un pueblo abandonado a la violencia en México: No podemos ni debemos acostumbrarnos a vivir así,,https://elpais.com/mexico/2025-04-18/teocaltiche-un-pueblo-abandonado-a-la-violencia-en-mexico-no-podemos-ni-debemos-acostumbrarnos-a-vivir-asi.html
CAMP-08,2021-11-26,Campeche,,,CJNG; Cártel del Pacífico y del Golfo; células delincuenciales con presencia en Campeche,,https://www.poresto.net/campeche/2021/11/26/cjng-cartel-del-pacifico-del-golfo-celulas-delincuenciales-con-presencia-en-campeche.html
CAMP-09,2023-07-28,Campeche,,,Otorgan amparo al fundador del CJNG; pidió revertir prisión preventiva,,http://campechehoy.mx/tag/cjng/
CAMP-10,2025-04-18,Campeche,,,El ascenso de 'La Firma' (2/7 partes),,https://solcampeche.mx/el-ascenso-de-la-firma-2-7-partes/
CAMP-11,2018-02-07,Colima,,,Fighting for the Plaza: CDS Vs CJNG in Pacific States,,https://www.borderlandbeat.com/2018/02/fighting-for-plaza-cds-vs-cjng-in.html
CAMP-12,2025-03-24,Jalisco,Teuchitlán,14091,Killing Camp Shows Horrors of CJNG Forced Recruitment,,https://insightcrime.org/news/killing-camp-in-mexico-shows-horrors-of-cjng-forced-recruitment/
CAMP-13,2025-03-24,Jalisco,Teuchitlán,14091,Campo de exterminio en México expone los horrores del reclutamiento forzado,,https://insightcrime.org/es/noticias/campo-exterminio-mexico-expone-horrores-reclutamiento-forzado-cjng/
CAMP-14,2022-10-23,Campeche,,,Ejecutado le robó millones al CJNG,,https://tribunacampeche.com/23/ejecutado-le-robo-millones-al-cjng/594728/
CAMP-15,2025-02-05,Tabasco,Villahermosa,27017,Cambian en Tabasco a mando militar por presuntos nexos con el Cártel Nueva Generación,,https://tribunacampeche.com/05/cambian-en-tabasco-a-mando-militar-por-presuntos-nexos-con-el-cartel-nueva-generacion/705768/
CAMP-16,2025-04-18,Campeche,,,CJNG – TELEMAR CAMPECHE,,https://telemarcampeche.com/tag/cjng/
CAMP-17,2018-02-03,Jalisco,Ocotlán,14061,Arde Ocotlán por narcobloqueo de familiares del CJNG contra Policía Federal,,https://jaliscorojo.com/2018/02/03/arde-ocotlan-por-narcobloqueo-de-familiares-del-cjng-contra-policia-federal/
CAMP-18,2023-08-11,Quintana Roo,Carmen,23003,Captura FGE a 'La Yolanda'; jefa de plaza del CJNG y responsable de reciente violencia en Q. Roo,,https://www.jorgecastronoriega.com/captura-fge-a-la-yolanda-jefa-de-plaza-del-cjng-y-responsable-de-reciente-violencia-en-q-roo/
CAMP-19,2023-08-31,México,,,Mexico: The Jalisco New Generation Cartel (CJNG); its activities; areas of operation; and influence; ability of the CJNG to track and retaliate against people who move to other areas of Mexico; the profiles of people they would be motivated to track and target (2021–August 2023),,https://irb-cisr.gc.ca/en/country-information/rir/Pages/index.aspx?doc=458872&pls=1
CAMP-20,2018-03-19,México,,,The Strategic Implications of the Cártel de Jalisco Nueva Generación,,https://digitalcommons.usf.edu/cgi/viewcontent.cgi?article=1661&context=jss
CAMP-21,2021-08-01,México,,,Mexico: The Jalisco New Generation Cartel (CJNG); its activities; areas of operation and influence; the ability of the CJNG to track and retaliate against people who move to other areas of Mexico; including Mérida; Campeche; Mexico City; and Cabo San Lucas; the profiles of people they would be motivated to track and target (2019–August 2021),,https://www.ecoi.net/en/document/2061281.html
CAMP-22,2020-06-01,México,,,The Violent Rise of Cártel de Jalisco Nueva Generación (CJNG),,https://digitalcommons.fiu.edu/srhreports/toc/toc/120/
CAMP-23,2021-09-08,México,,,Mexico: The crime situation in Mérida; Mexico City; Campeche; and Cabo San Lucas; organized crime and cartel groups active in these cities; the ability and motivation of organized crime groups and cartels active in other areas of Mexico; including the CJNG; to track and retaliate against people who relocate to these areas (2019–August 2021),,https://irb-cisr.gc.ca/en/country-information/rir/Pages/index.aspx?doc=458425
CAMP-24,2018-03-19,México,,,Policy Brief: The New Generation: Mexico’s Emerging Organized Crime Threat,,https://justiceinmexico.org/wp-content/uploads/2018/03/180319-Policy_Brief-CJNG.pdf
CAMP-25,2018-04-19,México,,,CJNG: la organización criminal donde todo queda en familia,,https://lasillarota.com/nacion/2018/4/19/cjng-la-organizacion-criminal-donde-todo-queda-en-familia-156948.html
CAMP-26,2018-04-23,México,,,CJNG: Los 5 casos de violencia que conmocionaron México,,https://www.jornada.com.mx/2018/04/23/politica/023n1pol
CAMP-27,2018-04-24,México,,,CJNG: los casos de violencia que conmocionaron México,,https://lasillarota.com/estados/2018/4/24/cjng-los-casos-de-violencia-que-conmocionaron-mexico-157276.html
CAMP-28,2024-10-02,Campeche,,,No fue una; sino tres presuntas narcomantas colocadas en distintos puntos de la ciudad capital,,https://tribunacampeche.com/02/no-fue-una-sino-tres-presuntas-narcomantas-colocadas-en-distintos-puntos-de-la-ciudad-capital/695234/
CAMP-29,2024-04-12,Campeche,,,Deja CJNG manta con amenazas contra secretaria de seguridad de Campeche,,https://www.jorgecastronoriega.com/deja-cjng-manta-con-amenazas-contra-secretaria-de-seguridad-de-campeche/
CAMP-30,2022-10-07,México,,,Problemas en el CJNG,,https://solcampeche.mx/problemas-en-el-cjng/
CAMP-31,2018-10-15,México,,,How Nemesio 'El Mencho' Oseguera became Mexico's most wanted man,,https://www.borderlandbeat.com/2018/10/how-nemesio-el-mencho-oseguera.html
CAMP-32,2018-08-20,México,,,El Mayo' is behind division of CJNG,,https://www.borderlandbeat.com/2018/08/el-mayo-is-behind-division-of-cjng.html
CAMP-33,2021-09-01,México,,,Mexico: The Jalisco New Generation Cartel (CJNG); its activities; areas of operation and influence; the ability of the CJNG to track and retaliate against people who move to other areas of Mexico; including Mérida; Campeche;Mexico City; and Cabo San Lucas; the profiles of people they would be motivated to track and target (2019–August 2021),,https://irb-cisr.gc.ca/en/country-information/rir/Pages/index.aspx?doc=458419
CAMP-34,2018-06-08,Campeche,Campeche,4001,Caen 6 chinos y 4 mexicanos del CJNG,,http://campechehoy.mx/2018/06/08/caen-6-chinos-y-4-mexicanos-del-cjng/
CAMP-35,2025-03-11,Jalisco,Teuchitlán,14091,Rancho asegurado en Teuchitlán Jalisco operaba como campo de exterminio del CJNG,,https://www.afmedios.com/rancho-asegurado-en-teuchitlan-jalisco-operaba-como-campo-de-exterminio-del-cjng/
CAMP-36,2019-05-23,Jalisco,Talpa de Allende,14092,Testigo revela detalles de los campos del CJNG: recluta niños; 'navys' y 'fuerzas Delta' de EU,,https://www.poresto.net/mexico/2019/5/23/testigo-revela-detalles-de-los-campos-del-cjng-recluta-ninos-navys-fuerzas-delta-de-eu.html
CAMP-37,2025-03-11,Jalisco,Teuchitlán,14091,Cae líder de red de reclutamiento del CJNG; operaba centro de adiestramiento en Teuchitlán Jalisco,,https://www.afmedios.com/cae-lider-de-red-de-reclutamiento-del-cjng-operaba-centro-de-adiestramiento-en-teuchitlan-jalisco/
CAMP-38,2018-10-16,México,,,Indictments against 11 high-level Mexican drug cartel members unsealed,,https://www.dea.gov/press-releases/2018/10/16/indictments-against-11-high-level-mexican-drug-cartel-members-unsealed
CAMP-39,2025-04-18,México,,,Jalisco New Generation Cartel,,https://en.wikipedia.org/wiki/Jalisco_New_Generation_Cartel
CAMP-40,2022-09-26,México,,,Mexico's New Generation Jalisco Cartel Coordinates Chaos in Bid to Free Comrades,,https://www.militantwire.com/p/mexicos-new-generation-jalisco-cartel
CAMP-41,2018-08-08,México,,,Tierra de narcocampamentos,,https://www.reporteindigo.com/opinion/Tierra-de-narcocampamentos-20180808-0011.html
CAMP-42,2025-03-20,Jalisco,,,Cronología del CJNG en Jalisco: 12 años de terror que dejaron 13 mil desaparecidos,,https://www.infobae.com/mexico/2025/03/20/cronologia-del-cjng-en-jalisco-12-anos-de-terror-que-dejaron-13-mil-desaparecidos/
CAMP-43,2025-03-15,Jalisco,Teuchitlán,14091,Centro de exterminio del CJNG operaba desde 2018; pero el alcalde afirma que desconocían su existencia,,https://www.noroeste.com.mx/nacional/centro-de-exterminio-del-cjng-operaba-desde-2018-pero-el-alcalde-afirma-que-desconocian-su-existencia-PA11110593
CAMP-44,2018-08-08,México,,,Tierra de narcocampamentos,,https://www.casede.org/BibliotecaCasede/casede-medios/Tierra-de-narcocampamentos-Reporte-Indigo.pdf
CAMP-45,2018-10-16,Estados Unidos,,,Justice Treasury and State Departments Announce Coordinated Enforcement Actions Against Mexican Drug Cartels,,https://www.dea.gov/press-releases/2018/10/16/justice-treasury-and-state-departments-announce-coordinated-enforcement
CAMP-46,2018-10-16,Campeche,,,Ofrece EE.UU. 10 mdd por 'El Mencho',,http://campechehoy.mx/2018/10/16/ofrece-ee-uu-10-mdd-por-el-mencho/
CAMP-47,2021-04-12,México,,,El Cártel del Tabaco se expande de la mano del CJNG,,https://www.proceso.com.mx/nacional/2021/4/12/el-cartel-del-tabaco-se-expande-de-la-mano-del-cjng-261835.html
CAMP-48,2025-03-15,México,,,El CJNG ya opera en 25 de los 32 estados y su poder está lejos de ser minado; muestran cifras,,https://www.sinembargo.mx/3665887/el-cjng-ya-opera-en-25-de-los-32-estados-y-su-poder-esta-lejos-de-ser-minado-muestran-cifras/
CAMP-49,2023-06-20,México,,,CJNG perdió presencia en varias entidades del país en tres años; según estudios,,https://www.infobae.com/mexico/2023/06/20/cjng-perdio-presencia-en-varias-entidades-del-pais-en-tres-anos-segun-estudios/
CAMP-50,2018-12-01,México,,,Crimen organizado y seguridad en México: Informe de diciembre de 2018,,https://www.gob.mx/cms/uploads/attachment/file/883801/CE_2018_12.pdf
CAMP-51,2021-03-18,Jalisco,Tlaquepaque,14067,Trascende video de 'El Cholo' capturado por el CJNG por órdenes de 'El Mencho',,https://www.lapalabradelcaribe.com/trasciende-video-de-el-cholo-capturado-por-el-cjng-por-ordenes-del-mencho/
CAMP-52,2018-11-02,Estado de México,,,La inminente incursión del CJNG en el Edomex,,https://lasillarota.com/metropoli/2018/11/2/la-inminente-incursion-del-cjng-en-el-edomex-172542.html
CAMP-53,2019-08-14,Campeche,,,CJNG declara la guerra al Cártel de 'El Abuelo',,http://campechehoy.mx/2019/08/14/cjng-declara-la-guerra-al-cartel-de-el-abuelo/
CAMP-54,2024-12-03,Campeche,Ciudad del Carmen,4002,Desplaza Pura Gente Nueva célula del Cártel Jalisco a Cártel de Sinaloa en Campeche,,https://tribunacampeche.com/03/desplaza-pura-gente-nueva-celula-del-cartel-jalisco-a-cartel-de-sinaloa-en-campeche/700783/
CAMP-55,2024-04-12,Campeche,,,CJNG cuelga manta amenazando a secretaria de Seguridad de Campeche Marcela Muñoz,,https://www.debate.com.mx/estados/CJNG-cuelga-manta-amenazando-a-secretaria-de-Seguridad-de-Campeche-Marcela-Munoz-20240412-0146.html
CAMP-56,2023-01-13,Campeche,Champotón,4003,CJNG: Cárteles se disputan plaza y llegan hasta Campeche,,https://www.informador.mx/mexico/CJNG-Carteles-se-disputan-plaza-y-llegan-hasta-Campeche-20230113-0113.html
CAMP-57,2024-10-22,Campeche,,,Reconocen en Campeche aumento en las extorsiones,,https://www.poresto.net/campeche/2024/10/22/reconocen-en-campeche-aumento-en-las-extorsiones-.html
CHH-01,2025-03-05,Chihuahua,Chihuahua,8020,Detienen y extraditan a EEUU a operador de La Línea y CJNG; habría participado en atentado contra Harfuch,,https://www.infobae.com/mexico/2025/03/05/detienen-y-extraditan-a-eeuu-a-operador-de-la-linea-y-cjng-habria-participado-en-atentado-contra-harfuch/
CHH-02,2024-10-31,Chihuahua,Ciudad Juárez,8037,EEUU sanciona a cinco narcotraficantes de La Línea; grupo ligado al CJNG y al Cártel de Juárez,,https://www.infobae.com/mexico/2024/10/31/eeuu-sanciona-a-cinco-narcotraficantes-de-la-linea-grupo-ligado-al-cjng-y-al-cartel-de-juarez/
CHH-03,2024-09-17,Jalisco,Tapalpa,14084,El 'Jaguar'; jefe de sicarios de 'El Chapo'; testifica en contra de 'El Menchito'; esto dijo,,https://lasillarota.com/nacion/2024/9/17/el-jaguar-jefe-de-sicarios-de-el-chapo-testifica-en-contra-de-el-menchito-esto-dijo-501844.html
CHH-04,2022-02-13,Chihuahua,Chihuahua,8020,Detienen en Chihuahua a 'El Fantasma'; presunto líder regional del CJNG en Zacatecas,,https://latinus.us/mexico/2022/2/13/detienen-en-chihuahua-el-fantasma-presunto-lider-regional-del-cjng-en-zacatecas-58716.html
CHH-05,2021-12-22,Chihuahua,Guadalupe y Calvo,8028,Dos nuevos cárteles en Chihuahua declaran la guerra al de Sinaloa: NCJNG y Nuevo Cártel de Juárez,,https://www.proceso.com.mx/reportajes/2021/12/22/dos-nuevos-carteles-en-chihuahua-declaran-la-guerra-al-de-sinaloa-ncjng-nuevo-cartel-de-juarez-277935.html
CHH-06,2024-11-01,Chihuahua,Ciudad Juárez,8037,Trafica ‘La Línea’ fentanilo del CJNG,,https://www.eldiariodechihuahua.mx/estado/2024/nov/01/trafica-la-linea-fentanilo-del-cjng-654248.html
CHH-07,2024-11-01,Chihuahua,Ciudad Juárez,8037,¿Quién es “El Chuyin”; presunto socio de La Línea sancionado por EEUU?,,https://www.infobae.com/mexico/2024/11/01/quien-es-el-chuyin-presunto-socio-de-la-linea-sancionado-por-eeuu/
CHH-08,2022-07-04,Chihuahua,Urique,8066,Se exacerba el terror en la Sierra Tarahumara: El CJNG anuncia su llegada,,https://www.proceso.com.mx/reportajes/2022/7/4/se-exacerba-el-terror-en-la-sierra-tarahumara-el-cjng-anuncia-su-llegada-288916.html
CHH-09,2017-05-27,Chihuahua,Ciudad Juárez,8037,El Cártel de Jalisco; el más poderoso en Chihuahua,,https://www.proceso.com.mx/reportajes/2017/5/27/el-cartel-de-jalisco-el-mas-poderoso-en-chihuahua-185013.html
CHH-10,2024-01-19,Chihuahua,Guadalupe y Calvo,8028,Persiste desplazamiento forzado en municipios de Chiapas y Chihuahua,,https://www.jornada.com.mx/2024/01/19/estados/026n1est
CHH-11,2021-02-16,Chihuahua,Jiménez,8036,Alertan alianza entre CJNG y La Línea contra el Cártel de Sinaloa,,https://lasillarota.com/nacion/2021/2/16/alertan-alianza-entre-cjng-la-linea-contra-el-cartel-de-sinaloa-267690.html
CHH-12,2022-02-08,Chihuahua,Ciudad Juárez,8037,Extorsionadores en Juárez piden aportaciones en nombre del CJNG,,https://oem.com.mx/elheraldodechihuahua/local/extorsionadores-en-juarez-piden-aportaciones-en-nombre-del-cjng-15172245
CHH-13,2017-04-19,Chihuahua,Ciudad Juárez,8037,Cártel de Jalisco Nueva Generación opera ya en Chihuahua,,https://oem.com.mx/elsoldemexico/mexico/cartel-de-jalisco-nueva-generacion-opera-ya-en-chihuahua-16601926
CHH-14,2022-08-11,Chihuahua,Ciudad Juárez,8037,Ahora en Ciudad Juárez; atacan tiendas y gasolineras; matan al menos 10; incluido el locutor Allan González,,https://www.proceso.com.mx/nacional/2022/8/11/ahora-en-ciudad-juarez-atacan-tiendas-gasolineras-matan-al-menos-10-incluido-el-locutor-allan-gonzalez-291374.html
CHH-15,2022-03-13,Chihuahua,Tuxtla Gutiérrez,7072,Capturan a líder de grupo delictivo 'Gente Nueva' y a miembro del CJNG,,https://www.tvazteca.com/aztecanoticias/lider-gente-nueva-cjng-jvgl
CHH-16,2024-01-08,Chihuahua,Guadalajara,14039,¿Por qué acusan de fraude a la empresa Yox Holding en Jalisco y otros estados?,,https://www.debate.com.mx/guadalajara/Por-que-acusan-de-FRAUDE-a-la-empresa-Yox-Holding-En-Jalisco-y-otros-estados-20240108-0216.html
CHH-17,2024-05-25,Chihuahua,Ciudad Juárez,8037,Detienen a dos presuntos criminales de lavado de dinero del Cártel de Sinaloa y CJNG en Estados Unidos,,https://oem.com.mx/elheraldodejuarez/local/detienen-a-dos-presuntos-criminales-de-lavado-de-dinero-del-cartel-de-sinaloa-y-cjng-en-estados-unidos-13654950
CHH-18,2017-03-28,Chihuahua,Ciudad Juárez,8037,Cae 'El Cochi Ratón'; líder del Cártel de Jalisco,,https://www.debate.com.mx/mexico/Cae-El-Cochi-Raton-lider-del-Cartel-de-Jalisco-20170328-0077.html
CHH-19,2017-09-27,Chihuahua,Chihuahua,8020,Asesinan a 14 personas en centro de adicciones de Chihuahua,,https://lasillarota.com/estados/2017/9/27/asesinan-14-personas-en-centro-de-adicciones-de-chihuahua-141069.html
CHH-20,2015-11-15,Chihuahua,Chihuahua,8020,Consignan al segundo del CJNG a penal de Chihuahua,,https://josecardenas.com/2015/11/consigan-al-segundo-del-cjng-a-penal-de-chihuahua/
CHH-21,2021-02-16,Chihuahua,Ciudad Juárez,8037,La violenta irrupción del CJNG en Chihuahua: estaría pactando con La Línea eliminar al Cártel de Sinaloa,,https://eldiariodelnoroeste.mx/noticias/2021/feb/16/la-violenta-irrupcion-del-cjng-en-chihuahua-estaria-pactando-con-la-linea-eliminar-al-cartel-de-sinaloa-598876.html
CHH-22,2018-06-12,Chihuahua,Puerto Vallarta,14067,Detienen a presunto contador del CJNG,,https://segundoasegundo.com/detienen-a-presunto-contador-del-cjng/
CHH-23,2020-07-02,Chihuahua,Hidalgo del Parral,8033,Atribuyen balaceras a ruptura entre el cártel Gente Nueva; Cártel de Sinaloa; Cártel de Juárez y CJNG,,https://oem.com.mx/elheraldodechihuahua/local/atribuyen-balaceras-a-ruptura-entre-el-cartel-gente-nueva-cartel-de-sinaloa-cartel-de-juarez-cjng-22724771
CHH-24,2025-02-14,Chihuahua,Ciudad Juárez,8037,Detienen a 'El Viejón'; líder del Cártel de Sinaloa en Ciudad Juárez; era buscado por el FBI,,https://www.elfinanciero.com.mx/estados/2025/02/14/detienen-a-el-viejon-lider-del-cartel-de-sinaloa-en-ciudad-juarez-era-buscado-por-el-fbi/
CHH-25,2023-10-31,Chihuahua,Ciudad Juárez,8037,El JL': esto se sabe del actual líder del Cártel de Juárez tras la captura de 'El Viceroy'; hermano de Amado Carrillo,,https://www.infobae.com/mexico/2023/10/31/el-jl-esto-se-sabe-del-actual-lider-del-cartel-de-juarez-tras-la-captura-de-el-viceroy-hermano-de-amado-carrillo/
CHH-26,2023-03-23,Chihuahua,Toluca,15083,Cayó 'El Minimi'; presunto líder de La Línea; grupo que estaría vinculada al CJNG,,https://www.infobae.com/mexico/2023/03/23/cayo-el-minimi-presunto-lider-de-la-linea-grupo-que-estaria-vinculada-al-cjng/
CHH-27,2024-07-31,Chihuahua,Ojinaga,8052,¿Quién es Alfredo “El PlayStation” Chávez; el narcotraficante buscado por la DEA que podría estar ocultándose en México?,,https://www.infobae.com/mexico/2024/07/31/quien-es-alfredo-el-playstation-chavez-el-narcotraficante-buscado-por-la-dea-que-podria-estar-ocultandose-en-mexico/
CHH-28,2024-06-28,Chihuahua,Zapopan,14120,César Cazarin Molina; 'Comandante Tornado'; sentenciado a 60 años; ¿qué delitos cometió el CJNG?,,https://www.elfinanciero.com.mx/nacional/2024/06/28/cesar-cazarin-molina-comandante-tornado-sentenciado-a-60-anos-que-delitos-cometio-cjng/
CHH-29,2022-03-03,Chihuahua,Colima,6004,¿Quién es 'La Vaca'; el narco liberado que declaró la guerra a sus aliadas del CJNG en Colima?,,https://www.infobae.com/america/mexico/2022/03/03/quien-es-la-vaca-el-narco-liberado-que-declaro-la-guerra-a-sus-aliadas-del-cjng-en-colima/
CHH-30,2022-12-22,Chihuahua,Tepic,18017,Detienen al 'Borrego'; brazo derecho de uno de los líderes del CJNG,,https://www.eldiariodechihuahua.mx/nacional/2022/dec/22/detienen-al-borrego-brazo-derecho-de-uno-de-los-lideres-del-cjng-473223.html
CHIS-01,2024-12-25,Chiapas,Cintalapa,7019,Operativos intensivos contra el CJNG en Chiapas resultan en aseguramientos clave,,https://www.contramuro.com/operativos-contra-cjng-chiapas/
CHIS-02,2024-01-05,Chiapas,Frontera Comalapa,7034,CJNG' y el 'Cártel de Sinaloa' reactivan enfrentamientos en Chiapas,,https://www.jornada.com.mx/noticia/2024/01/05/estados/2018cjng2019-y-el-2018cartel-de-sinaloa2019-reactivan-enfrentamientos-en-chiapas-431
CHIS-03,2023-05-30,Chiapas,Chicomuselo,7019,Violencia; desplazados y fosas: guerra entre CJNG y Chapos llega a Chiapas,,https://lasillarota.com/estados/2023/5/30/violencia-desplazados-fosas-guerra-entre-cjng-chapos-llega-chiapas-430955.html
CHIS-04,2025-01-04,Chiapas,Frontera Comalapa,7034,CJNG: Catean cinco ranchos de la organización criminal y rescatan a extranjeros cautivos,,https://www.informador.mx/mexico/CJNG-Catean-cinco-ranchos-de-la-organizacion-criminal-y-rescatan-a-extranjeros-cautivos-20250104-0044.html
CHIS-05,2018-08-15,Chiapas,Frontera Comalapa,7034,Fuerzas federales y estatales capturan en Chiapas a 30 presuntos integrantes del CJNG,,https://www.proceso.com.mx/nacional/2018/8/15/fuerzas-federales-estatales-capturan-en-chiapas-30-presuntos-integrantes-del-cjng-210503.html
CHIS-06,2025-03-15,Chiapas,Tuxtla Gutiérrez,7019,Cártel de Jalisco Nueva Generación fortalece su dominio en Chiapas tras caída de Cártel de Sinaloa,,https://www.sinaloahoy.com.mx/portal/cartel-de-jalisco-nueva-generacion-fortalece-su-dominio-en-chiapas-tras-caida-de-cartel-de-sinaloa/
CHIS-07,2025-01-05,Chiapas,Puerto Chiapas,7019,Cártel de Sinaloa y CJNG; los amos de Chiapas,,https://solyucatan.mx/cartel-de-sinaloa-y-cjng-los-amos-de-chiapas/
CHIS-08,2018-08-16,Chiapas,Frontera Comalapa,7034,Caen 30 presuntos integrantes del CJNG en Chiapas,,https://eldiariony.com/2018/08/16/caen-30-presuntos-integrantes-del-cjng-en-chiapas/
CHIS-09,2018-08-17,Chiapas,Frontera Comalapa,7034,Capturan en Chiapas a 48 del Cártel de Jalisco Nueva Generación,,https://www.razon.com.mx/mexico/2018/08/17/capturan-en-chiapas-a-48-del-cartel-de-jalisco-nueva-generacion/
CHIS-10,2023-09-18,Chiapas,,7000,Gary Monje; CJNG; extradición Chiapas,,https://www.dallasnews.com/espanol/al-dia/estados-unidos/2023/09/18/gary-monje-cjng-extradicion-chiapas/
CHIS-11,2018-08-16,Chiapas,Frontera Comalapa,7034,Detienen en Chiapas a presunta célula del Cártel Jalisco Nueva Generación (CJNG),,https://www.chiapasparalelo.com/noticias/chiapas/2018/08/detienen-en-chiapas-a-presunta-celula-del-cartel-jalisco-nueva-generacion-cjng/
CHIS-12,2018-08-16,Chiapas,Frontera Comalapa,7034,Detienen a 48 personas vinculadas con el CJNG en Chiapas,,https://www.yucatan.com.mx/mexico/2018/08/16/detienen-a-48-personas-vinculadas-con-el-cjng-en-chiapas.html
CHIS-13,2018-08-15,Chiapas,Frontera Comalapa,7034,Capturan a 30 presuntos integrantes del CJNG en Chiapas,,https://riodoce.mx/2018/08/15/capturan-a-30-presuntos-integrantes-del-cjng-en-chiapas/
CHIS-14,2018-08-16,Chiapas,Frontera Comalapa,7034,Detienen a 48 presuntos integrantes del CJNG en Chiapas,,https://www.ntv.com.mx/2018/08/16/detienen-a-48-presuntos-integrantes-del-cjng-en-chiapas/
CHIS-15,2025-03-25,Jalisco,Teuchitlán,14093,Campo de exterminio en México expone los horrores del reclutamiento forzado,,https://insightcrime.org/es/noticias/campo-exterminio-mexico-expone-horrores-reclutamiento-forzado-cjng/
CHIS-16,2025-03-14,Chiapas,,7000,Alianzas con grupos locales: la clave del CJNG para adentrarse en Chiapas y confrontar al Cártel de Sinaloa,,https://www.infobae.com/mexico/2025/03/14/alianzas-con-grupos-locales-la-clave-del-cjng-para-adentrarse-en-chiapas-y-confrontar-al-cartel-de-sinaloa/
CHIS-17,2018-08-15,Chiapas,Frontera Comalapa,7034,Capturan a 30 presuntos integrantes del CJNG en Chiapas,,https://www.debate.com.mx/policiacas/Capturan-a-30-presuntos-integrantes-del-CJNG-en-Chiapas-20180815-0278.html
CHIS-18,2025-04-09,Chiapas,Tuxtla Gutiérrez,7019,Desarticulan célula del CJNG en Chiapas,,https://www.jornada.com.mx/noticia/2025/04/09/estados/desarticulan-celula-del-cjng-en-chiapas
CHIS-19,2024-02-26,Chiapas,Frontera Comalapa,7034,Así fue como el CJNG se infiltró en Chiapas pese al dominio del Cártel de Sinaloa; según WSJ,,https://www.infobae.com/mexico/2024/02/26/asi-fue-como-el-cjng-se-infiltro-en-chiapas-pese-al-dominio-del-cartel-de-sinaloa-segun-wsj/
CHIS-20,2018-08-16,Chiapas,Frontera Comalapa,7034,Capturan en Chiapas 48 presuntos integrantes de una célula del CJNG,,https://mvsnoticias.com/nacional/2018/8/16/capturan-en-chiapas-48-presuntos-integrantes-de-una-celula-del-cjng-383445.html
CHIS-21,2023-09-15,Chiapas,Altamirano,7004,CJNG; la brutal masacre contra una familia de catequistas católicos en Chiapas,,https://www.prensalibre.com/internacional/cjng-la-brutal-masacre-contra-una-familia-de-catequistas-catolicos-en-chiapas/
CHIS-22,2024-10-10,Chiapas,Altos de Chiapas,7000,Gobierno niega conflicto armado en Chiapas mientras violencia exacerba crisis humanitaria,,https://avispa.org/gobierno-niega-conflicto-armado-en-chiapas-mientras-violencia-exacerba-crisis-humanitaria/
CHIS-23,2025-01-10,Chiapas,Ocosingo,7058,Chiapas nuevamente: términos de la conflictividad actual; el nuevo eje dominante: CDS vs CJNG (Parte II),,https://www.sdpnoticias.com/opinion/chiapas-nuevamente-terminos-de-la-conflictividad-actual-el-nuevo-eje-dominante-cds-vs-cjng-parte-ii/
CHIS-24,2018-08-16,Chiapas,Frontera Comalapa,7034,Detienen a 48 presuntos integrantes del CJNG en Chiapas,,https://www.zonacentronoticias.com/2018/08/detienen-a-48-presuntos-integrantes-del-cjng-en-chiapas/
CHIS-25,2018-08-16,Chiapas,Frontera Comalapa,7034,Suman 48 detenidos vinculados con el CJNG en Chiapas,,https://www.eluniversal.com.mx/estados/suman-48-detenidos-vinculados-con-el-cjng-en-chiapas/
CHIS-26,2018-08-16,Chiapas,Frontera Comalapa,7034,Desarticulan célula del CJNG que operaba en Chiapas,,https://gabycoutino.com/2018/08/16/desarticulan-celula-del-cjng-que-operaba-en-chiapas/
CHIS-27,2018-08-16,Chiapas,Frontera Comalapa,7034,Detienen en Chiapas a 48 presuntos integrantes del Cártel Jalisco Nueva Generación,,https://www.sinembargo.mx/3458006/detienen-en-chiapas-a-48-presuntos-integrantes-del-cartel-jalisco-nueva-generacion/
CHIS-28,2018-08-16,Chiapas,Frontera Comalapa,7034,Grupo interinstitucional detiene a 48 supuestos integrantes del CJNG,,https://chiapas.quadratin.com.mx/sucesos/grupo-interistitucional-detiene-a-48-supuestos-integrantes-del-cjng/
CHIS-29,2018-08-16,Chiapas,Frontera Comalapa,7034,Capturan en Chiapas a 30 presuntos integrantes del CJNG,,https://www.diaadiatamaulipas.com/2018/08/capturan-en-chiapas-30-presuntos.html
CHIS-30,2023-09-24,Chiapas,Chicomuselo,7019,Crece tensión en Chiapas por disputa entre CJNG y el ‘Cártel de Sinaloa’,,https://www.jornada.com.mx/noticia/2023/09/24/estados/crece-tension-en-chiapas-por-disputa-entre-cjng-y-el-2018cartel-de-sinaloa2019-8724
CHIS-31,2023-11-06,Chiapas,Chicomuselo,7019,Cuatro integrantes del CJNG fueron vinculados a proceso en Chiapas,,https://www.capitalmexico.com.mx/estados/chiapas/cuatro-integrantes-del-cjng-fueron-vinculados-a-proceso-en-chiapas/
CHIS-32,2025-04-18,Chiapas,Tuxtla Gutiérrez,7019,Comisión de DDHH de México acusa al Ejército de graves violaciones por matar a 6 migrantes,,https://es-us.noticias.yahoo.com/comisi%C3%B3n-ddhh-m%C3%A9xico-acusa-ej%C3%A9rcito-163623928.html
CHIS-33,2023-03-15,Chiapas,Tapachula,7089,Sedena revela el mapa criminal en Chiapas: operan cárteles y Mara Salvatrucha,,https://contralinea.com.mx/interno/semana/sedena-revela-el-mapa-criminal-en-chiapas-operan-carteles-y-mara-salvatrucha/
CHIS-34,2023-11-06,Chiapas,Chicomuselo,7019,¿Cómo ha logrado expandirse el CJNG? Evidencia reciente de Chiapas,,https://www.elfinanciero.com.mx/opinion/eduardo-guerrero-gutierrez/2023/11/06/como-ha-logrado-expandirse-el-cjng-evidencia-reciente-de-chiapas/
CHIS-35,2025-01-30,Chiapas,Bella Vista,7013,CJNG: Cae segundo alcalde en Chiapas; ahora por presuntos nexos con el narco,,https://www.informador.mx/mexico/CJNG-Cae-segundo-alcalde-en-Chiapas-ahora-por-presuntos-nexos-con-el-narco-20250130-0084.html
CHIS-36,2025-03-24,Chiapas,Tuxtla Gutiérrez,7019,LASTRA; detenido en CDMX por reclutar y adiestrar para el CJNG; había sido reportado como desaparecido en Chiapas en 2020,,https://elsoldechiapas.com/lastra-detenido-en-cdmx-por-reclutar-y-adiestrar-para-el-cjng-habia-sido-reportado-como-desaparecido-en-chiapas-en-2020/
CHIS-37,2025-04-06,Chiapas,Tuxtla Gutiérrez,7019,LIGAN con el CJNG buques de huachicol,,https://elsoldechiapas.com/ligan-con-el-cjng-buques-de-huachicol/
CHIS-38,2025-04-16,Chiapas,Tuxtla Gutiérrez,7019,ASÍ LAVABAN millones de dólares el Cártel de Sinaloa y CJNG con envíos a China; revela EE.UU.,,https://elsoldechiapas.com/asi-lavaban-millones-de-dolares-el-cartel-de-sinaloa-y-cjng-con-envios-a-china-revela-ee-uu/
CHIS-39,2024-11-21,Chiapas,Tuxtla Gutiérrez,7019,Cártel de Jalisco Nueva Generación en Chiapas: Un desafío para la seguridad,,https://tuxtladigital.com/2024/11/21/cartel-de-jalisco-nueva-generacion-en-chiapas-un-desafio-para-la-seguridad/
CHIS-40,2024-11-18,Chiapas,Jaltenango,7019,Bloqueos en Chiapas: el CJNG presiona para sacar al Ejército del estado,,https://laverdadnoticias.com/crimen/bloqueos-en-chiapas-el-cjng-presiona-para-sacar-al-ejercito-del-estado-20241118
CHIS-41,2024-11-15,Chiapas,Jaltenango,7019,Ahora es al revés: el CJNG presiona pero para al Ejército de Chiapas,,https://www.narcoenmexico.com/2024/11/ahora-es-al-reves-el-cjng-presiona-pero.html
CHIS-42,2024-05-07,Chiapas,Tuxtla Gutiérrez,7019,Violencia y corrupción: la herencia de Rutilio Escandón en Chiapas,,https://reportemaya.mx/2024/05/07/violencia-y-corrupcion-la-herencia-de-rutilio-escandon-en-chiapas/
CHIS-43,2025-03-24,Chiapas,Frontera Comalapa,7034,Caen dos en Chiapas que llevaban armas; cocaína y una gorra del CJNG,,https://www.infobae.com/mexico/2025/03/24/caen-dos-en-chiapas-que-llevaban-armas-cocaina-y-una-gorra-del-cjng/
CHIS-44,2025-03-22,Chiapas,Cintalapa,7019,Ranchos El Zapote y sicarios fueron asegurados por fuerzas federales en Cintalapa; presumiblemente usados por el CJNG,,https://elsoldechiapas.com/ranchos-el-zapote-y-sicarios-fueron-asegurados-por-fuerzas-federales-en-cintalapa-presumiblemente-usados-por-el-cjng/
CHIS-45,2025-03-21,Chiapas,Tonalá,7093,Incautan en Chiapas vehículo que transportaba más 4 millones de pesos en cocaína,,https://elsoldechiapas.com/incautan-en-chiapas-vehiculo-que-transportaba-mas-4-millones-de-pesos-en-cocaina/
CHIS-46,2025-03-20,Chiapas,Villaflores,7058,Guardia Nacional abate a sicarios del Cártel de Chiapas tras agresión en Villaflores,,https://elsoldechiapas.com/guardia-nacional-abate-a-sicarios-del-cartel-de-chiapas-tras-agresion-en-villaflores/
CHIS-47,2025-03-19,Chiapas,Marqués de Comillas,7057,Emboscan convoy de la Sedena en Marqués de Comillas; Chiapas; se reporta la muerte de un militar,,https://elsoldechiapas.com/emboscan-convoy-de-la-sedena-en-marques-de-comillas-chiapas-se-reporta-la-muerte-de-un-militar/
CHIS-48,2025-03-15,Chiapas,Frontera Comalapa,7034,Más de 100 personas han desaparecido en Frontera Comalapa; Chiapas; por la actividad delincuencial de los últimos años,,https://elsoldechiapas.com/mas-de-100-personas-han-desaparecido-en-frontera-comalapa-chiapas-por-la-actividad-delincuencial-de-los-ultimos-anos/
CHIS-49,2025-03-14,Chiapas,Tapachula,7089,Chiapas rompe récord de violencia: tuvo 22 homicidios en un día,,https://oem.com.mx/elsoldemexico/mexico/chiapas-rompe-record-de-violencia-tuvo-22-homicidios-en-un-dia-13092635
CHIS-50,2025-03-13,Chiapas,Tuxtla Gutiérrez,7019,Pese a ola de violencia; solo un líder criminal en Chiapas ha sido detenido,,https://oem.com.mx/elsoldemexico/mexico/pese-a-ola-de-violencia-solo-un-lider-criminal-en-chiapas-ha-sido-detenido-16609051
CHIS-51,2025-03-10,Chiapas,Comitán,7028,Gatilleros de 'El Mayo'; el azote de Chiapas,,https://solyucatan.mx/gatilleros-de-el-mayo-el-azote-de-chiapas/
CHIS-52,2025-01-08,Chiapas,Tuxtla Gutiérrez,7019,Detienen a cinco presuntos integrantes del CJNG en Tuxtla Gutiérrez; Chiapas,,https://www.debate.com.mx/estados/Detienen-a-cinco-presuntos-integrantes-del-CJNG-en-Tuxtla-Gutierrez-Chiapas-20250108-0127.html
CHIS-53,2025-01-12,Chiapas,Frontera Sierra,7000,Nueva cartografía del crimen en Chiapas; los cárteles que operan en el estado,,https://oem.com.mx/elsoldemexico/mexico/nueva-cartografia-del-crimen-en-chiapas-los-carteles-que-operan-en-el-estado-15425441
CHIS-54,2025-01-10,Chiapas,Frontera Comalapa,7034,Chiapas otra vez en guerra,,https://oem.com.mx/elsoldemexico/mexico/chiapas-otra-vez-en-guerra-15403686
CHIS-55,2025-01-09,Chiapas,Tapachula,7089,Extorsiona crimen ahora a plataneros de Chiapas,,https://elsoldechiapas.com/extorsiona-crimen-ahora-a-plataneros-de-chiapas/
CHIS-56,2025-01-08,Chiapas,Ocosingo,7058,Narcoviolencia en Chiapas: Hombre suplicó a todos los varones de Chejel que regresen a defender su comunidad,,https://elsoldechiapas.com/narcoviolencia-en-chiapas-hombre-suplico-a-todos-los-varones-de-chejel-que-regresen-a-defender-su-comunidad/
CHIS-57,2024-05-14,Chiapas,Chicomuselo,7019,CJNG y de Sinaloa atacan CFE Chiapas; 11 muertos en Chicomuselo,,https://www.yucatan.com.mx/mexico/2024/05/14/cjng-y-de-sinaloa-atacan-cfe-chiapas-11-muertos-en-chicomuselo.html
CHIS-58,2025-01-13,Chiapas,Sierra Madre,7000,Mantienen al Ejército sin acceso a Sierra de Chiapas,,https://oem.com.mx/elsoldemexico/mexico/mantienen-al-ejercito-sin-acceso-a-sierra-de-chiapas-13093332
CHIS-59,2018-08-16,Chiapas,Frontera Comalapa,7034,Detienen en Chiapas a presunta célula del Cártel Jalisco Nueva Generación (CJNG),,https://www.chiapasparalelo.com/noticias/chiapas/2018/08/detienen-en-chiapas-a-presunta-celula-del-cartel-jalisco-nueva-generacion-cjng/
CHIS-60,2019-10-10,Veracruz,Xalapa,30067,Liberan a presunto líder del CJNG en Veracruz; ahora dirige un diario respaldado por Morena,,https://www.chiapasparalelo.com/noticias/chiapas/2019/10/liberan-a-presunto-lider-del-cjng-en-veracruz-ahora-dirige-un-diario-respaldado-por-morena/
23-04-25-NOTA-01,2024-11-11,Jalisco,Guadalajara,14039,En Jalisco SSPC detiene a La Güera presunta operadora de los Mayos en Colima,,https://www.angulo7.com.mx/2024/nacional/en-jalisco-sspc-detiene-a-la-guera-presunta-operadora-de-los-mayos-en-colima/591346/
23-04-25-NOTA-02,2024-12-28,Guerrero,Acapulco,12001,Detenido en Acapulco El Panadero líder de una célula criminal en la ciudad del Pacífico,,https://elpais.com/mexico/2024-12-28/detenido-en-acapulco-el-panadero-lider-de-una-celula-criminal-en-la-ciudad-del-pacifico.html
23-04-25-NOTA-03,2015-11-06,Baja California Sur,Los Cabos,3008,Detienen a El Gus,,https://www.noroeste.com.mx/nacional/detienen-a-el-gus-CVNO19105
23-04-25-NOTA-04,2024-02-13,Estado de México,Naucalpan,15057,Capturan a integrantes del Cártel Nuevo Imperio en Naucalpan les encuentran pistolas y vehículos de alta gama,,https://www.infobae.com/mexico/2024/02/13/capturan-a-integrantes-del-cartel-nuevo-imperio-en-naucalpan-les-encuentran-pistolas-y-vehiculos-de-alta-gama/
23-04-25-NOTA-05,2025-03-10,Estado de México,Ecatepec,15033,Líder de Los 300 de Ecatepec fue recluido en el penal de Tenango,,https://lajornadaestadodemexico.com/lider-de-los-300-de-ecatepec-fue-recluido-en-el-penal-de-tenango/
23-04-25-NOTA-06,2025-03-12,Chiapas,Comitán de Domínguez,7019,Cae en Chiapas La Chicharra líder máximo de Los Huistas y el criminal más buscado en Guatemala,,https://www.infobae.com/mexico/2025/03/12/cae-en-chiapas-la-chicharra-lider-maximo-de-los-huistas-y-el-criminal-mas-buscado-en-guatemala/
23-04-25-NOTA-07,2025-04-20,Guerrero,Chilpancingo,12014,Los Ardillos: líderes y autoridades coludidas en Chilpancingo,,https://graficos.gruporeforma.com/los-ardillos-elementor-alcaldesa/
23-04-25-NOTA-08,2025-01-20,Chiapas,San Cristóbal de las Casas,7078,Detienen a líder de Los Motonetos en San Cristóbal de las Casas,,https://www.jornada.com.mx/2025/01/20/estados/029n1est
23-04-25-NOTA-09,2025-03-15,Chiapas,Yajalón,7101,Detienen a El Chorizo líder del grupo criminal Karma en Yajalón,,https://www.telediario.mx/comunidad/chiapas-detienen-a-el-chorizo-lider-del-grupo-criminal-karma
23-04-25-NOTA-10,2025-03-31,Chiapas,Tila,7102,FGE de Chiapas ofrece recompensa por presunto líder criminal en Tila,,https://www.milenio.com/estados/fge-de-chiapas-ofrece-recompensa-por-presunto-lider-criminal-en-tila
23-04-25-NOTA-11,2025-03-10,Estado de México,Ecatepec,15033,Operativo conjunto logra captura de líder criminal,,https://www.elmanana.com/noticias/nacional/operativo-conjunto-logra-captura-de-lider-criminal/5949776
23-04-25-NOTA-12,2025-02-22,Morelos,Cuernavaca,17001,Cae El Mija líder de La Familia Michoacana en Morelos,,https://www.nacion321.com/estados/2025/02/22/cae-el-mija-lider-de-la-familia-michoacana-en-morelos/
23-04-25-NOTA-13,2025-02-05,Tabasco,Centro,27002,El licenciado Tomasín o El 12 líder de La Barredora es vinculado a proceso,,https://www.excelsior.com.mx/nacional/el-licenciado-tomasin-o-el-12-lider-de-la-barredora-es-vinculado-a-proceso/1698248
23-04-25-NOTA-14,2024-11-14,Guerrero,Tecoanapa,12060,Detienen a La Garza cabecilla de Los Ardillos en Tecoanapa Guerrero,,https://www.jornada.com.mx/noticia/2024/11/14/politica/detienen-a-la-garza-cabecilla-de-los-ardillos-en-tecoanapa-guerrero-6304
23-04-25-NOTA-15,2025-03-24,Sinaloa,Culiacán,25006,Vinculan a dos detenidos en Culiacán con Fuerzas Especiales Avendaño brazo armado de Los Chapitos,,https://oem.com.mx/elsoldesinaloa/policiaca/vinculan-a-dos-detenidos-en-culiacan-con-fuerzas-especiales-avendano-brazo-armado-de-los-chapitos-22341931
23-04-25-NOTA-16,2025-04-12,Oaxaca,Matías Romero,20057,Identifican a grupo criminal ligado al CJNG en Matías Romero Oaxaca se dedican al huachicol robo y extorsión,,https://www.infobae.com/mexico/2025/04/12/identifican-a-grupo-criminal-ligado-al-cjng-en-matias-romero-oaxaca-se-dedican-al-huachicol-robo-y-extorsion/
23-04-25-NOTA-17,2025-03-20,Querétaro,Querétaro,22001,Detienen Alfa 1 líder criminal del Cártel del Golfo,,https://abcnoticias.mx/nacional/2025/3/20/detienen-alfa-1-lider-criminal-del-cartel-del-golfo-243643.html
23-04-25-NOTA-18,2025-03-27,Estado de México,Toluca,15093,Cae objetivo relevante de la Familia Michoacana que operaba en el Edomex es investigado por homicidio,,https://www.infobae.com/mexico/2025/03/27/cae-objetivo-relevante-de-la-familia-michoacana-que-operaba-en-el-edomex-es-investigado-por-homicidio/
23-04-25-NOTA-19,2025-02-25,Michoacán,Zacapu,16097,¿Quién es El Chuy líder criminal capturado en Zacapu?,,https://heraldodemexico.com.mx/nacional/2025/2/25/quien-es-el-chuy-lider-criminal-capturado-en-zacapu-679025.html
23-04-25-NOTA-20,2025-02-19,Michoacán,Pátzcuaro,16067,Los Panchitos Michoacán quiénes son cártel que opera en Pátzcuaro aliados del CJNG Francisco Manuel Flores El Panchito,,https://www.elfinanciero.com.mx/nacional/2025/02/19/los-panchitos-michoacan-quienes-son-cartel-que-opera-en-patzcuaro-aliados-del-cjng-francisco-manuel-flores-el-panchito/
23-04-25-NOTA-21,2025-03-15,Michoacán,Apatzingán,16009,Capturan a familiares de presunto líder extorsionador de limoneros y aguacateros,,https://forbes.com.mx/capturan-a-familiares-de-presunto-lider-extorsionador-de-limoneros-y-aguacateros/
23-04-25-NOTA-22,2025-02-19,Sinaloa,Culiacán,25006,Detienen a El Güerito presunto lugarteniente de Los Chapitos,,https://www.jornada.com.mx/noticia/2025/02/19/politica/detienen-a-2018el-guerito2019-presunto-lugarteniente-de-2018los-chapitos2019-8722
23-04-25-NOTA-23,2025-03-23,Ciudad de México,Cuajimalpa,9010,José Gregorio N de desaparecido a presunto reclutador del CJNG el caso que conecta Chiapas y Jalisco,,https://www.infobae.com/mexico/2025/03/23/jose-gregorio-n-de-desaparecido-a-presunto-reclutador-del-cjng-el-caso-que-conecta-chiapas-y-jalisco/
23-04-25-NOTA-24,2023-12-12,Oaxaca,Santiago Jamiltepec,20077,Detienen a Manuel Iglesias 'El Pantera' hijo de presidenta municipal de Jamiltepec Oaxaca,,https://www.milenio.com/policia/detienen-hijo-presidenta-jamiltepec-crimen-organizado
23-04-25-NOTA-25,2025-01-06,Chiapas,Frontera Comalapa,7034,¿Quién es José Antonio Villatoro el alcalde de Frontera Comalapa detenido y vinculado con el CJNG?,,https://www.infobae.com/mexico/2025/01/06/quien-es-jose-antonio-villatoro-el-alcalde-de-frontera-comalapa-detenido-y-vinculado-con-el-cjng/
23-04-25-NOTA-26,2025-03-20,Michoacán,Coalcomán,16017,Alcaldesa de Michoacán con presuntos nexos con el CJNG y El Mencho podría ir a juicio político MC niega notificación,,https://www.infobae.com/mexico/2025/03/20/alcaldesa-de-michoacan-con-presuntos-nexos-con-el-cjng-y-el-mencho-podria-ir-a-juicio-politico-mc-niega-notificacion/
23-04-25-NOTA-27,2025-02-09,Estado de México,Santo Tomás de los Plátanos,15084,Arrestan al alcalde electo de Santo Tomás Edomex prófugo 50 días,,https://www.jornada.com.mx/2025/02/09/estados/021n1est
24-04-25-NOTA-01,2025-01-10,Tamaulipas,Aldama,28003,Recompensas millonarias en Tamaulipas estos son los líderes criminales más buscados,,https://laverdadnoticias.com/crimen/recompensas-millonarias-en-tamaulipas-estos-son-los-lideres-criminales-mas-buscados-20250110
24-04-25-NOTA-02,2025-04-10,Tamaulipas,San Fernando,28033,Cae El Flaco jefe regional de los Zetas Vieja Escuela en San Fernando Tamaulipas,,https://www.infobae.com/mexico/2025/04/10/cae-el-flaco-jefe-regional-de-los-zetas-vieja-escuela-en-san-fernando-tamaulipas/
24-04-25-NOTA-03,2025-04-09,Jalisco,Tlajomulco de Zúñiga,14098,En Jalisco detienen a La Barbie uno de los líderes de Los Zetas la Vieja Escuela narco delincuente,,https://oem.com.mx/elsoldemexico/mexico/en-jalisco-detienen-a-la-barbie-uno-de-los-lideres-de-los-zetas-la-vieja-escuela-narco-delincuente-15922396?token=-1535492604
24-04-25-NOTA-04,2025-03-24,Guanajuato,Celaya,11010,Detienen a El Agus principal colaborador de El Marro líder Cártel Santa Rosa FGR Marina,,https://oem.com.mx/elsoldemexico/mexico/detienen-a-el-agus-principal-colaborador-de-el-marro-lider-cartel-santa-rosa-fgr-marina-15927181
24-04-25-NOTA-05,2025-03-17,Guanajuato,Cortazar,11013,Detienen a 2 hombres vinculados a El Marro,,https://aristeguinoticias.com/editorial/1703/mexico/detienen-a-2-hombres-vinculados-a-el-marro/
24-04-25-NOTA-06,2025-03-17,Ciudad de México,Ciudad de México,9000,FGR detiene a dos sujetos ligados a El Marro Ciudad de México Guanajuato Cártel de Santa Rosa de Lima El Flaco El Bala,,https://oem.com.mx/elsoldemexico/mexico/fgr-detiene-a-dos-sujetos-ligados-a-el-marro-ciudad-de-mexico-guanajuato-cartel-de-santa-rosa-de-lima-el-flaco-el-bala-16613205
24-04-25-NOTA-07,2020-06-24,San Luis Potosí,San Luis Potosí,24028,Capturan a Noé Lara Belman El Puma ex mano derecha de El Marro,,https://lasillarota.com/guanajuato/estado/2020/6/24/capturan-noe-lara-belman-el-puma-ex-mano-derecha-de-el-marro-235172.html
24-04-25-NOTA-08,2020-06-24,Baja California,Tijuana,2004,Vinculan a proceso a La Vieja cercano a El Marro del Cártel de Santa Rosa de Lima,,https://www.capitalmexico.com.mx/cdmx/vinculan-a-proceso-a-la-vieja-cercano-a-el-marro-del-cartel-de-santa-rosa-de-lima/
24-04-25-NOTA-09,2020-02-22,Guanajuato,Celaya,11010,El Tortugo uno de los principales operadores de El Marro fue detenido en Celaya,,https://lasillarota.com/estados/2020/2/22/el-tortugo-uno-de-los-principales-operadores-de-el-marro-fue-detenido-en-celaya-217957.html
24-04-25-NOTA-10,2025-04-24,Jalisco,Ixtlahuacán del Río,14045,Presunta detención de El Doble R habría detonado narcobloqueos en tres estados Saucedo,,https://aristeguinoticias.com/2404/mexico/presunta-detencion-de-el-doble-r-habria-detonado-narcobloqueos-en-tres-estados-saucedo/
24-04-25-NOTA-11,2024-12-02,Guanajuato,Apaseo el Grande,11003,Cae Burras Prietas líder de banda criminal dedicada al robo de autotransportes rescatan a 5 migrantes,,https://www.eluniversal.com.mx/nacion/cae-burras-prietas-lider-de-banda-criminal-dedicada-al-robo-de-autotransportes-rescatan-a-5-migrantes/
24-04-25-NOTA-12,2025-01-31,Guanajuato,León,11020,Cae El Flaco líder de una célula del CJNG en Guanajuato es investigado por el asesinato de dos custodios en León,,https://www.infobae.com/mexico/2025/01/31/cae-el-flaco-lider-de-una-celula-del-cjng-en-guanajuato-es-investigado-por-el-asesinato-de-dos-custodios-en-leon/
24-04-25-NOTA-13,2025-03-28,Guanajuato,Silao,11030,Vinculan a proceso Big Mama presunto integrante del CJNG por robo de transporte secuestro,,https://mvsnoticias.com/nacional/policiaca/2025/3/28/vinculan-proceso-big-mama-presunto-integrante-del-cjng-por-robo-de-transporte-secuestro-685223.html
24-04-25-NOTA-14,2025-02-27,Guanajuato,León,11020,Así capturaron Don Arturo y La Chepina del CJNG en León,,https://www.excelsior.com.mx/nacional/asi-capturaron-don-arturo-y-la-chepina-del-cjng-en-leon/1702254
24-04-25-NOTA-15,2024-11-16,Jalisco,Zapopan,14067,Detienen a Armando Gómez Núñez alias Delta 1 operador del CJNG en Zapopan,,https://www.jornada.com.mx/2024/11/16/politica/011n3pol
24-04-25-NOTA-16,2024-11-18,Morelos,Amacuzac,17004,Detienen a Jaime Bahena Landa alias La Parka líder de La Nueva Familia Michoacana en Morelos,,https://latinus.us/mexico/2024/11/18/la-parka-integrante-de-la-familia-michoacana-detenido-en-morelos-fue-candidato-regidor-del-pt-en-amacuzac-128661.html
24-04-25-NOTA-17,2023-12-23,Ciudad de México,Ciudad de México,9000,Sentencian a 43 años de cárcel a El Betito ex líder de la Unión Tepito,,https://www.infobae.com/mexico/2023/12/23/sentencian-a-43-anos-de-carcel-a-el-betito-ex-lider-de-la-union-tepito/
24-04-25-NOTA-18,2025-01-22,Ciudad de México,Benito Juárez,9015,A prisión El Tiger operador financiero de La Unión Tepito,,https://www.excelsior.com.mx/comunidad/a-prision-el-tiger-operador-financiero-la-union-tepito/1696214
24-04-25-NOTA-19,2024-07-29,Quintana Roo,Cancún,23005,El Huguito detenido en Cancún se queda en el Reclusorio Oriente por homicidio,,https://www.eluniversal.com.mx/metropoli/el-huguito-detenido-en-cancun-se-queda-en-el-reclusorio-oriente-por-homicidio/
24-04-25-NOTA-20,2024-08-04,Estado de México,Almoloya de Alquisiras,15006,Dan prisión vitalicia a El 47 jefe de plaza de la Familia Michoacana en el Edomex por homicidio,,https://www.infobae.com/mexico/2024/08/04/dan-prision-vitalicia-a-el-47-jefe-de-plaza-de-la-familia-michoacana-en-el-edomex-por-homicidio/
24-04-25-NOTA-21,2020-08-19,Ciudad de México,Cuauhtémoc,9005,Cae El Galleta líder delictivo de la zona del Ajusco,,https://es-us.noticias.yahoo.com/cae-galleta-l%C3%ADder-delictivo-zona-192745066.html
24-04-25-NOTA-22,2018-10-02,Baja California Sur,La Paz,3003,La caída de El Colores y/o El Patreño,,https://zetatijuana.com/2018/10/la-caida-de-el-colores-y-o-el-patreno/
24-04-25-NOTA-23,2018-08-30,Nuevo León,Monterrey,19039,Detienen en Monterrey a El Pelonchas y El Penco líderes del Cártel del Golfo,,https://aristeguinoticias.com/3008/mexico/detienen-en-monterrey-a-el-pelonchas-y-el-penco-lideres-del-cartel-del-golfo/
24-04-25-NOTA-24,2018-08-24,Nuevo León,Monterrey,19039,Cae La Yegua líder de célula criminal del Cártel del Golfo,,https://oem.com.mx/elsoldelalaguna/mexico/cae-la-yegua-lider-de-celula-criminal-del-cartel-del-golfo-18722785
24-04-25-NOTA-25,2018-08-15,Chihuahua,Ciudad Juárez,8037,Cae El Sexto el último líder del Cártel de Juárez,,https://lasillarota.com/nacion/2018/8/15/cae-el-sexto-el-ultimo-lider-del-cartel-de-juarez-166574.html
24-04-25-NOTA-26,2018-02-16,Guanajuato,San José Iturbide,11031,El Cholo de la Familia Michoacana jefe de sicarios de El Ojos,,https://lasillarota.com/metropoli/2018/2/16/el-cholo-de-la-familia-michoacana-jefe-de-sicarios-de-el-ojos-152234.html
24-04-25-NOTA-27,2011-10-18,Estado de México,Ecatepec de Morelos,15033,Detienen a líder de grupo criminal La Barredora,,https://animalpolitico.com/2011/10/detienen-a-lider-de-grupo-criminal-la-barredora
24-04-25-NOTA-28,2024-05-18,Querétaro,Querétaro,22006,Caen El Tuto; El May y El Zapato; líderes criminales en la CDMX capturados en Querétaro,,https://heraldodemexico.com.mx/nacional/2024/5/18/caen-el-tuto-el-may-el-zapato-lideres-criminales-en-la-cdmx-capturados-en-queretaro-604181.html
24-04-25-NOTA-29,2024-01-27,Sinaloa,Sinaloa,25027,Quién es Edwin Antonio Rubio López; alias el Max; detenido en Sinaloa y cuál es su relación con el Mayo Zambada,,https://www.ambito.com/mexico/informacion-general/quien-es-edwin-antonio-rubio-lopez-alias-el-max-detenido-sinaloa-y-cual-es-su-relacion-el-mayo-zambada-n6073396
24-04-25-NOTA-30,2024-11-19,Estado de México,Huixquilucan,15037,Confirman 20 años de cárcel para El Indio; líder del Cártel de los Beltrán Leyva detenido en el Edomex,,https://www.infobae.com/mexico/2024/11/19/confirman-20-anos-de-carcel-para-el-indio-lider-del-cartel-de-los-beltran-leyva-detenido-en-el-edomex/
24-04-25-NOTA-31,2020-01-29,Coahuila,Torreón,5031,Quién es El Irakí; el enemigo público número 1 de Chihuahua señalado por la masacre de 21 personas este fin de semana,,https://www.infobae.com/america/mexico/2020/01/29/quien-es-el-iraki-el-enemigo-publico-numero-1-de-chihuahua-senalado-por-la-masacre-de-21-personas-este-fin-de-semana/
24-04-25-NOTA-32,2024-11-28,Estado de México,Cuautitlán Izcalli,15029,Procesan a El Buchanans involucrado en ataque a bar Bling Bling Edomex,,https://www.milenio.com/policia/procesan-a-el-buchanans-involucrado-en-ataque-a-bar-bling-bling-edomex
24-04-25-NOTA-33,2024-05-16,Ciudad de México,Tlalpan,9010,Así fue como autoridades aprehendieron a El Tortas; líder de la Fuerza Anti-Unión,,https://www.infobae.com/mexico/2024/05/16/asi-fue-como-autoridades-aprehendieron-a-el-tortas-lider-de-la-fuerza-anti-union/
24-04-25-NOTA-34,2023-12-25,Chihuahua,Chihuahua,8020,Dictan prisión preventiva a El Cumbias; líder de Gente Nueva del Cártel de Sinaloa,,https://www.infobae.com/mexico/2023/12/25/dictan-prision-preventiva-a-el-cumbias-lider-de-gente-nueva-del-cartel-de-sinaloa/
24-04-25-NOTA-35,2023-01-03,Chihuahua,Ciudad Juárez,8037,¿Quién es El Neto; líder de Los Mexicles de Ciudad Juárez?,,https://www.excelsior.com.mx/nacional/el-neto-lider-mexicles-ciudad-juarez/1561853
24-04-25-NOTA-36,2018-10-30,Ciudad de México,Xochimilco,9016,Unión Tepito: cae El Cabezas; presunto líder de Fuerza Anti Unión Tepito,,https://www.milenio.com/policia/union-tepito-detienen-cabezas-presunto-lider-fuerza-anti-union-tepito
24-04-25-NOTA-37,2020-01-29,Chihuahua,Nuevo Casas Grandes,8045,Detienen a autor intelectual de masacre de familia LeBarón,,https://www.noroeste.com.mx/nacional/detienen-a-autor-intelectual-de-masacre-de-familia-lebaron-KANO1215681
24-04-25-NOTA-38,2024-02-19,CDMX,Iztacalco,9006,Cae 'Pícoro'; líder del Cártel de Tláhuac; acusado de invadir casas y predios,,https://aristeguinoticias.com/1902/mexico/cae-picoro-lider-del-cartel-de-tlahuac-acusado-de-invadir-casas-y-predios/
24-04-25-NOTA-39,2024-02-20,CDMX,Cuauhtémoc,9002,Detienen a 11 miembros de escisión del cártel de Tláhuac; uno es el líder,,https://www.jornada.com.mx/2024/02/20/capital/028n1cap
24-04-25-NOTA-40,2025-04-23,CDMX,Venustiano Carranza,9015,Detienen líder célula CJNG cartel Jalisco Nueva Generacion en CDMX narcotrafico,,https://oem.com.mx/elsoldemexico/mexico/detienen-lider-celula-cjng-cartel-jalisco-nueva-generacion-en-cdmx-narcotrafico-16610370
24-04-25-NOTA-41,2019-08-21,Guerrero,Chilapa de Álvarez,12027,Detienen en Guerrero a Zenén Nava; El Chaparro; el otro líder de Los Rojos,,https://zetatijuana.com/2019/08/detienen-en-guerrero-a-zenen-nava-el-chaparro-el-otro-lider-de-los-rojos/
24-04-25-NOTA-42,2022-12-06,Estado de México,Nicolás Romero,15058,‘El Mirra’; uno de los criminales más buscados del Edomex; pasará el resto de su vida en prisión,,https://www.infobae.com/america/mexico/2022/12/06/el-mirra-uno-de-los-criminales-mas-buscados-del-edomex-pasara-el-resto-de-su-vida-en-prision/
24-04-25-NOTA-43,2024-04-09,CDMX,Xochimilco,9016,Vinculan a proceso a ‘El Cindy’; presunto líder del Cártel de Tláhuac,,https://www.jornada.com.mx/noticia/2024/04/09/capital/vinculan-a-proceso-a-2018el-cindy2019-presunto-lider-del-cartel-de-tlahuac-7722
24-04-25-NOTA-44,2024-04-18,Ciudad de México,Cuauhtémoc,9002,Cae integrante de La Unión Tepito identificado como El Yerson,,https://www.milenio.com/policia/cae-integrante-de-la-union-tepito-identificado-como-el-yerson
24-04-25-NOTA-45,2024-10-16,Ciudad de México,Cuauhtémoc,9002,Así es como la UIF y la SEIDO buscan acabar de raíz con La Unión Tepito en la CDMX,,https://www.infobae.com/mexico/2024/10/16/asi-es-como-la-uif-y-la-seido-buscan-acabar-de-raiz-con-la-union-tepito-en-la-cdmx/
CSV

updated = 0
not_found = []

CSV.parse(csv_data, headers: true) do |row|
  link = row['link']&.strip
  next if link.blank?

  hit = Hit.find_by(link: link)

  if hit
    hit.update(user_id: 1164)
    puts "✅ Hit ##{hit.id} actualizado con user_id 1164"
    updated += 1
  else
    puts "❌ Hit no encontrado para link: #{link}"
    not_found << link
  end
end

puts "🎯 Total de hits actualizados: #{updated}"
puts "🔍 Links no encontrados: #{not_found.count}"
